"""
Infection Journey Analysis Script

This script analyzes the infection_journeys.csv file generated by the AMR simulation
to provide insights into individual patient journeys and population-level outcomes.

Features:
1. View individual patient journeys with timeline visualization
2. Create stacked graphs of infection outcomes by day
3. Calculate 30-day mortality probability from infection onset
4. Summary statistics and outcome analysis

Author: Generated for AMR simulation analysis
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend for saving files only
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

class InfectionJourneyAnalyzer:
    def __init__(self, csv_file="infection_journeys.csv", output_dir="output_graphs/journey_analysis"):
        """Initialize the analyzer with the journey data."""
        print(f"Loading infection journey data from {csv_file}...")
        self.df = pd.read_csv(csv_file)
        self.output_dir = output_dir
        
        # Create output directory if it doesn't exist
        import os
        os.makedirs(output_dir, exist_ok=True)
        
        self.process_data()
        print(f"Loaded {len(self.df)} journey snapshots for {self.df['journey_id'].nunique()} unique journeys")
        print(f"Figures will be saved to: {output_dir}")
        
    def process_data(self):
        """Process and clean the loaded data."""
        # Convert boolean columns
        bool_cols = ['sepsis', 'hospital_acquired', 'infection_identified', 'resistance_testing_done']
        for col in bool_cols:
            self.df[col] = self.df[col].astype(bool)
            
        # Create treatment status
        self.df['is_treated'] = self.df['current_drugs'].notna() & (self.df['current_drugs'] != "")
        
        # Create infection state categories
        self.df['infection_state'] = 'Unknown'
        self.df.loc[self.df['sepsis'] == True, 'infection_state'] = 'Sepsis'
        self.df.loc[(self.df['sepsis'] == False) & (self.df['is_treated'] == True), 'infection_state'] = 'Treated'
        self.df.loc[(self.df['sepsis'] == False) & (self.df['is_treated'] == False), 'infection_state'] = 'Not Treated'
        
        # Process resolution types
        self.df['resolution_type'] = self.df['resolution_type'].fillna('Ongoing')
        
        # Create journey summaries
        self.journey_summary = self._create_journey_summary()
        
    def _create_journey_summary(self):
        """Create summary statistics for each journey."""
        summary_stats = []
        
        for journey_id in self.df['journey_id'].unique():
            journey_data = self.df[self.df['journey_id'] == journey_id].copy()
            journey_data = journey_data.sort_values('day_of_journey')
            
            summary = {
                'journey_id': journey_id,
                'individual_id': journey_data['individual_id'].iloc[0],
                'age_at_onset': journey_data['age_at_onset'].iloc[0],
                'sex': journey_data['sex'].iloc[0],
                'region': journey_data['region_living'].iloc[0],
                'primary_bacteria': journey_data['primary_bacteria'].iloc[0],
                'syndrome': journey_data['syndrome'].iloc[0],
                'immunodeficiency': journey_data['immunodeficiency'].iloc[0],
                'hospital_acquired': journey_data['hospital_acquired'].iloc[0],
                'duration_days': journey_data['day_of_journey'].max(),
                'max_bacteria_level': journey_data['primary_bacteria_level'].max(),
                'developed_sepsis': journey_data['sepsis'].any(),
                'was_treated': journey_data['is_treated'].any(),
                'treatment_failures': journey_data['treatment_failures'].max(),
                'resolution_type': self._determine_actual_resolution(journey_data),
                'died': self._determine_actual_resolution(journey_data) == 'Death',
                'died_within_30_days': (self._determine_actual_resolution(journey_data) == 'Death') and (journey_data['day_of_journey'].max() <= 30)
            }
            summary_stats.append(summary)
            
        return pd.DataFrame(summary_stats)
    
    def view_individual_journey(self, journey_id=None, individual_id=None):
        """View detailed timeline for a specific journey."""
        if journey_id is not None:
            journey_data = self.df[self.df['journey_id'] == journey_id].copy()
        elif individual_id is not None:
            journey_data = self.df[self.df['individual_id'] == individual_id].copy()
        else:
            # Show first available journey
            journey_data = self.df[self.df['journey_id'] == self.df['journey_id'].iloc[0]].copy()
            
        if journey_data.empty:
            print("No journey found with the specified criteria.")
            return
            
        journey_data = journey_data.sort_values('day_of_journey')
        journey_id = journey_data['journey_id'].iloc[0]
        individual_id = journey_data['individual_id'].iloc[0]
        
        print(f"\n{'='*80}")
        print(f"INFECTION JOURNEY ANALYSIS - Journey ID: {journey_id}, Individual ID: {individual_id}")
        print(f"{'='*80}")
        
        # Patient demographics
        print(f"Patient Demographics:")
        print(f"  Age at onset: {journey_data['age_at_onset'].iloc[0]} days ({journey_data['age_at_onset'].iloc[0]/365.25:.1f} years)")
        print(f"  Sex: {journey_data['sex'].iloc[0]}")
        print(f"  Region: {journey_data['region_living'].iloc[0]}")
        print(f"  Immunodeficiency: {journey_data['immunodeficiency'].iloc[0]}")
        
        # Infection characteristics
        print(f"\nInfection Characteristics:")
        print(f"  Primary bacteria: {journey_data['primary_bacteria'].iloc[0]}")
        print(f"  Syndrome: {journey_data['syndrome'].iloc[0]}")
        print(f"  Hospital acquired: {journey_data['hospital_acquired'].iloc[0]}")
        print(f"  Journey duration: {journey_data['day_of_journey'].max()} days")
        print(f"  Final resolution: {journey_data['resolution_type'].iloc[-1]}")
        
        # Create timeline visualization
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 10))
        fig.suptitle(f'Journey Timeline - ID: {journey_id}', fontsize=14, fontweight='bold')
        
        days = journey_data['day_of_journey']
        
        # Bacteria level over time
        ax1.plot(days, journey_data['primary_bacteria_level'], 'b-', marker='o', linewidth=2, markersize=4)
        ax1.set_title('Primary Bacteria Level')
        ax1.set_xlabel('Day of Journey')
        ax1.set_ylabel('Bacteria Level')
        ax1.grid(True, alpha=0.3)
        
        # Immunity and toxicity levels
        ax2.plot(days, journey_data['immunity_level'], 'g-', marker='s', label='Immunity', linewidth=2, markersize=4)
        ax2.plot(days, journey_data['toxicity_level'], 'r-', marker='^', label='Toxicity', linewidth=2, markersize=4)
        ax2.set_title('Immunity & Toxicity Levels')
        ax2.set_xlabel('Day of Journey')
        ax2.set_ylabel('Level')
        ax2.legend()
        ax2.grid(True, alpha=0.3)
        
        # Treatment status
        treatment_status = journey_data['is_treated'].astype(int)
        sepsis_status = journey_data['sepsis'].astype(int) * 2
        ax3.fill_between(days, 0, treatment_status, alpha=0.6, color='blue', label='Treated', step='mid')
        ax3.fill_between(days, treatment_status, treatment_status + sepsis_status, alpha=0.6, color='red', label='Sepsis', step='mid')
        ax3.set_title('Treatment & Sepsis Status')
        ax3.set_xlabel('Day of Journey')
        ax3.set_ylabel('Status')
        ax3.set_yticks([0, 1, 2, 3])
        ax3.set_yticklabels(['None', 'Treated', 'Sepsis', 'Both'])
        ax3.legend()
        ax3.grid(True, alpha=0.3)
        
        # Hospital status
        hospital_mapping = {'NotInHospital': 0, 'Hospital': 1, 'ICU': 2}
        hospital_numeric = journey_data['hospital_status'].map(hospital_mapping)
        ax4.step(days, hospital_numeric, where='mid', linewidth=2, marker='o', markersize=4)
        ax4.set_title('Hospital Status')
        ax4.set_xlabel('Day of Journey')
        ax4.set_ylabel('Status')
        ax4.set_yticks([0, 1, 2])
        ax4.set_yticklabels(['Not in Hospital', 'Hospital', 'ICU'])
        ax4.grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        # Save the figure
        filename = f"journey_{journey_id}_individual_{individual_id}_timeline.png"
        filepath = f"{self.output_dir}/{filename}"
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        print(f"Saved individual journey plot: {filepath}")
        
        plt.close()  # Close figure to free memory
        
        # Print detailed day-by-day progression
        print(f"\nDay-by-Day Progression:")
        print(f"{'Day':>3} {'Bacteria':>8} {'Immunity':>8} {'Toxicity':>8} {'Treated':>7} {'Sepsis':>6} {'Hospital':>10}")
        print("-" * 65)
        
        for _, row in journey_data.iterrows():
            treated = 'Yes' if row['is_treated'] else 'No'
            sepsis = 'Yes' if row['sepsis'] else 'No'
            print(f"{row['day_of_journey']:>3} {row['primary_bacteria_level']:>8.3f} {row['immunity_level']:>8.3f} "
                  f"{row['toxicity_level']:>8.3f} {treated:>7} {sepsis:>6} {row['hospital_status']:>10}")
    
    def plot_infection_states_over_time(self, max_days=30):
        """Create stacked bar chart of infection states by day."""
        print(f"\nCreating infection states visualization (first {max_days} days)...")
        
        # Filter to first N days for readability
        daily_data = self.df[self.df['day_of_journey'] <= max_days].copy()
        
        # Count states by day
        state_counts = daily_data.groupby(['day_of_journey', 'infection_state']).size().unstack(fill_value=0)
        
        # Create stacked bar chart
        fig, ax = plt.subplots(figsize=(14, 8))
        
        colors = {'Not Treated': '#FF6B6B', 'Treated': '#4ECDC4', 'Sepsis': '#45B7D1', 'Unknown': '#96CEB4'}
        state_counts.plot(kind='bar', stacked=True, ax=ax, color=[colors.get(col, '#95A5A6') for col in state_counts.columns])
        
        ax.set_title(f'Infection States Over Time (First {max_days} Days)', fontsize=14, fontweight='bold')
        ax.set_xlabel('Day of Journey')
        ax.set_ylabel('Number of Individuals')
        ax.legend(title='Infection State', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.grid(True, alpha=0.3, axis='y')
        
        plt.xticks(rotation=45)
        plt.tight_layout()
        
        # Save the figure
        filename = f"infection_states_stacked_first_{max_days}_days.png"
        filepath = f"{self.output_dir}/{filename}"
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        print(f"Saved infection states plot: {filepath}")
        
        plt.close()  # Close figure to free memory
        
        return state_counts
    
    def calculate_30_day_mortality(self):
        """Calculate and visualize 30-day mortality probability."""
        print("\nCalculating 30-day mortality analysis...")
        
        # Filter journeys that either died within 30 days or survived at least 30 days
        mortality_analysis = []
        
        for journey_id in self.journey_summary['journey_id'].unique():
            journey_info = self.journey_summary[self.journey_summary['journey_id'] == journey_id].iloc[0]
            
            # Include if journey lasted at least 30 days OR ended in death
            if journey_info['duration_days'] >= 30 or journey_info['died']:
                mortality_analysis.append({
                    'journey_id': journey_id,
                    'died_within_30_days': journey_info['died_within_30_days'],
                    'duration_days': min(journey_info['duration_days'], 30),
                    'age_at_onset': journey_info['age_at_onset'],
                    'sex': journey_info['sex'],
                    'primary_bacteria': journey_info['primary_bacteria'],
                    'developed_sepsis': journey_info['developed_sepsis'],
                    'was_treated': journey_info['was_treated']
                })
        
        mortality_df = pd.DataFrame(mortality_analysis)
        
        if len(mortality_df) == 0:
            print("No journeys available for 30-day mortality analysis.")
            return None
        
        # Calculate overall 30-day mortality rate
        overall_mortality = mortality_df['died_within_30_days'].mean()
        print(f"Overall 30-day mortality rate: {overall_mortality:.1%} ({mortality_df['died_within_30_days'].sum()}/{len(mortality_df)} cases)")
        
        # Create mortality analysis plots
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 10))
        fig.suptitle('30-Day Mortality Analysis', fontsize=14, fontweight='bold')
        
        # Mortality by bacteria type
        bacteria_mortality = mortality_df.groupby('primary_bacteria')['died_within_30_days'].agg(['count', 'sum', 'mean']).reset_index()
        bacteria_mortality = bacteria_mortality[bacteria_mortality['count'] >= 5]  # At least 5 cases
        bacteria_mortality = bacteria_mortality.sort_values('mean', ascending=True)
        
        if len(bacteria_mortality) > 0:
            ax1.barh(range(len(bacteria_mortality)), bacteria_mortality['mean'], color='crimson', alpha=0.7)
            ax1.set_yticks(range(len(bacteria_mortality)))
            ax1.set_yticklabels([name.replace('_', ' ').title() for name in bacteria_mortality['primary_bacteria']])
            ax1.set_xlabel('30-Day Mortality Rate')
            ax1.set_title('Mortality by Bacteria Type')
            ax1.grid(True, alpha=0.3, axis='x')
        
        # Mortality by sepsis development
        sepsis_mortality = mortality_df.groupby('developed_sepsis')['died_within_30_days'].mean()
        ax2.bar(['No Sepsis', 'Developed Sepsis'], sepsis_mortality.values, color=['lightblue', 'darkred'], alpha=0.7)
        ax2.set_ylabel('30-Day Mortality Rate')
        ax2.set_title('Mortality by Sepsis Development')
        ax2.grid(True, alpha=0.3, axis='y')
        
        # Mortality by treatment status
        treatment_mortality = mortality_df.groupby('was_treated')['died_within_30_days'].mean()
        ax3.bar(['Not Treated', 'Treated'], treatment_mortality.values, color=['orange', 'green'], alpha=0.7)
        ax3.set_ylabel('30-Day Mortality Rate')
        ax3.set_title('Mortality by Treatment Status')
        ax3.grid(True, alpha=0.3, axis='y')
        
        # Age distribution of deaths vs survivors
        died_ages = mortality_df[mortality_df['died_within_30_days']]['age_at_onset'] / 365.25
        survived_ages = mortality_df[~mortality_df['died_within_30_days']]['age_at_onset'] / 365.25
        
        ax4.hist([died_ages, survived_ages], bins=20, alpha=0.7, label=['Died', 'Survived'], color=['red', 'blue'])
        ax4.set_xlabel('Age at Onset (years)')
        ax4.set_ylabel('Frequency')
        ax4.set_title('Age Distribution: Deaths vs Survivors')
        ax4.legend()
        ax4.grid(True, alpha=0.3, axis='y')
        
        plt.tight_layout()
        
        # Save the figure
        filename = "30_day_mortality_analysis.png"
        filepath = f"{self.output_dir}/{filename}"
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        print(f"Saved mortality analysis plot: {filepath}")
        
        plt.close()  # Close figure to free memory
        
        return mortality_df
    
    def detect_death_day(self, journey_data):
        """Detect the day when death likely occurred based on static values"""
        if len(journey_data) < 10:  # Need sufficient data points
            return None
            
        # Look for patterns indicating death (static values for extended periods)
        for start_idx in range(5, len(journey_data) - 5):  # Start checking after day 5
            current_row = journey_data.iloc[start_idx]
            
            # Check if the next 5+ days have identical values (indicating death/simulation stop)
            static_count = 0
            for check_idx in range(start_idx, min(start_idx + 10, len(journey_data))):
                check_row = journey_data.iloc[check_idx]
                
                # Check if key values are identical (indicating simulation stopped)
                if (abs(check_row['primary_bacteria_level'] - current_row['primary_bacteria_level']) < 0.001 and
                    abs(check_row['immunity_level'] - current_row['immunity_level']) < 0.001 and
                    abs(check_row['toxicity_level'] - current_row['toxicity_level']) < 0.001 and
                    check_row['sepsis'] == current_row['sepsis'] and
                    check_row['is_treated'] == current_row['is_treated']):
                    static_count += 1
                else:
                    break
            
            # If we found 5+ consecutive identical days, death likely occurred
            if static_count >= 5:
                return current_row['day_of_journey']
        
        return None
    
    def determine_death_cause(self, death_row):
        """Determine the likely cause of death based on final state"""
        causes = []
        
        # High toxicity death
        if death_row['toxicity_level'] > 3.5:
            causes.append("Toxicity")
        
        # Sepsis death
        if death_row['sepsis']:
            causes.append("Sepsis")
        
        # Severe infection death
        if death_row['primary_bacteria_level'] > 3.0:
            causes.append("Severe infection")
        
        # Default if no clear cause identified
        if not causes:
            causes.append("Multi-organ failure")
        
        return " + ".join(causes)
    
    def _determine_actual_resolution(self, journey_data):
        """Determine the actual resolution, detecting death if present"""
        # Check if death occurred (overrides original resolution)
        death_day = self.detect_death_day(journey_data)
        if death_day:
            return 'Death'
        
        # Otherwise use the original resolution from the data
        return journey_data['resolution_type'].iloc[-1]
    
    def generate_text_report(self):
        """Generate comprehensive text report file with detailed journey listings."""
        filename = f"{self.output_dir}/infection_journeys_detailed_report.txt"
        
        with open(filename, 'w') as f:
            # Write header
            f.write("="*80 + "\n")
            f.write("DETAILED INFECTION JOURNEY ANALYSIS REPORT\n")
            f.write("="*80 + "\n")
            f.write(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Total journeys: {len(self.journey_summary)}\n")
            f.write(f"Total snapshots: {len(self.df):,}\n\n")
            
            # Summary statistics
            f.write("SUMMARY STATISTICS\n")
            f.write("-" * 40 + "\n")
            f.write(f"Average journey length: {self.df.groupby('journey_id')['day_of_journey'].max().mean():.1f} days\n")
            f.write(f"Journeys with sepsis: {self.journey_summary['developed_sepsis'].sum()} ({self.journey_summary['developed_sepsis'].mean()*100:.1f}%)\n")
            f.write(f"Journeys with treatment: {self.journey_summary['was_treated'].sum()} ({self.journey_summary['was_treated'].mean()*100:.1f}%)\n")
            f.write(f"Hospital acquired infections: {self.journey_summary['hospital_acquired'].sum()} ({self.journey_summary['hospital_acquired'].mean()*100:.1f}%)\n\n")
            
            # Resolution type breakdown
            f.write("JOURNEY OUTCOMES\n")
            f.write("-" * 40 + "\n")
            resolution_counts = self.journey_summary['resolution_type'].value_counts()
            for resolution, count in resolution_counts.items():
                percentage = count / len(self.journey_summary) * 100
                f.write(f"  {resolution}: {count:,} ({percentage:.1f}%)\n")
            f.write("\n")
            
            # Bacteria breakdown
            f.write("BACTERIA DISTRIBUTION\n")
            f.write("-" * 40 + "\n")
            bacteria_counts = self.journey_summary['primary_bacteria'].value_counts().head(15)
            for bacteria, count in bacteria_counts.items():
                percentage = count / len(self.journey_summary) * 100
                f.write(f"  {bacteria.replace('_', ' ').title()}: {count:,} ({percentage:.1f}%)\n")
            f.write("\n")
            
            # Detailed individual journey listings
            f.write("="*80 + "\n")
            f.write("DETAILED INDIVIDUAL JOURNEY LISTINGS\n")
            f.write("="*80 + "\n\n")
            
            # Sort journeys by ID for consistent ordering
            for idx, (_, journey) in enumerate(self.journey_summary.sort_values('journey_id').iterrows(), 1):
                journey_id = journey['journey_id']
                journey_data = self.df[self.df['journey_id'] == journey_id].copy()
                journey_data = journey_data.sort_values('day_of_journey')
                
                f.write(f"JOURNEY #{idx} (ID: {journey_id})\n")
                f.write("-" * 60 + "\n")
                
                # Patient demographics
                f.write(f"Patient ID: {journey['individual_id']}\n")
                f.write(f"Age at onset: {journey['age_at_onset']} days ({journey['age_at_onset']/365.25:.1f} years)\n")
                f.write(f"Sex: {journey['sex']}\n")
                f.write(f"Region: {journey['region']}\n")
                f.write(f"Immunodeficiency: {journey['immunodeficiency']}\n\n")
                
                # Infection characteristics
                f.write(f"Primary bacteria: {journey['primary_bacteria'].replace('_', ' ').title()}\n")
                f.write(f"Syndrome: {journey['syndrome']}\n")
                f.write(f"Hospital acquired: {journey['hospital_acquired']}\n")
                f.write(f"Journey duration: {journey['duration_days']} days\n")
                f.write(f"Maximum bacteria level: {journey['max_bacteria_level']:.3f}\n")
                f.write(f"Developed sepsis: {journey['developed_sepsis']}\n")
                f.write(f"Received treatment: {journey['was_treated']}\n")
                f.write(f"Treatment failures: {journey['treatment_failures']}\n")
                # Show corrected resolution (detect death if present)
                actual_resolution = self._determine_actual_resolution(journey_data)
                if actual_resolution != journey['resolution_type']:
                    f.write(f"Final resolution: {actual_resolution} (originally recorded as: {journey['resolution_type']})\n\n")
                else:
                    f.write(f"Final resolution: {actual_resolution}\n\n")
                
                # Day-by-day progression (show ALL days until death)
                f.write("Day-by-day progression:\n")
                f.write("Day | Bacteria | Immunity | Toxicity | Treated | Sepsis | Hospital    | Death | Notes\n")
                f.write("-" * 95 + "\n")
                
                # Identify key milestone days for annotations
                treatment_starts = journey_data[journey_data['is_treated'] & ~journey_data['is_treated'].shift(1, fill_value=False)]
                sepsis_starts = journey_data[journey_data['sepsis'] & ~journey_data['sepsis'].shift(1, fill_value=False)]
                hospital_changes = journey_data[journey_data['hospital_status'] != journey_data['hospital_status'].shift(1, fill_value='')]
                
                treatment_start_days = set(treatment_starts['day_of_journey'].tolist())
                sepsis_start_days = set(sepsis_starts['day_of_journey'].tolist())
                hospital_change_days = set(hospital_changes['day_of_journey'].tolist())
                
                # Detect death by looking for static values (indicating simulation stopped processing)
                death_day = self.detect_death_day(journey_data)
                
                # Show days until death (or all days if no death detected)
                last_day_to_show = death_day if death_day else journey_data['day_of_journey'].max()
                
                for _, row in journey_data.iterrows():
                    day = row['day_of_journey']
                    
                    # Stop showing days after death
                    if death_day and day > death_day:
                        break
                        
                    treated = 'Yes' if row['is_treated'] else 'No '
                    sepsis = 'Yes' if row['sepsis'] else 'No '
                    
                    # Determine death status and cause
                    death_status = "No "
                    death_cause = ""
                    if death_day and day == death_day:
                        death_status = "Yes"
                        death_cause = self.determine_death_cause(row)
                    
                    # Add notes for key events
                    notes = []
                    if day in treatment_start_days:
                        notes.append("Treatment started")
                    if day in sepsis_start_days:
                        notes.append("Sepsis onset")
                    if day in hospital_change_days:
                        notes.append(f"Hospital: {row['hospital_status']}")
                    if death_cause:
                        notes.append(f"Death: {death_cause}")
                    
                    note_str = "; ".join(notes) if notes else ""
                    
                    f.write(f"{day:3d} | {row['primary_bacteria_level']:8.3f} | {row['immunity_level']:8.3f} | "
                           f"{row['toxicity_level']:8.3f} | {treated:7} | {sepsis:6} | "
                           f"{row['hospital_status']:11} | {death_status:5} | {note_str}\n")
                
                # Add summary if death was detected
                if death_day:
                    f.write(f"\n*** DEATH DETECTED ON DAY {death_day} - Journey terminated ***\n")
                
                f.write("\n" + "="*80 + "\n\n")
        
        print(f"Detailed text report saved: {filename}")
        return filename

    def generate_summary_report(self):
        """Generate comprehensive summary report."""
        print(f"\n{'='*80}")
        print("INFECTION JOURNEY ANALYSIS SUMMARY REPORT")
        print(f"{'='*80}")
        print(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        print(f"\nDataset Overview:")
        print(f"  Total journey snapshots: {len(self.df):,}")
        print(f"  Unique journeys: {self.df['journey_id'].nunique():,}")
        print(f"  Unique individuals: {self.df['individual_id'].nunique():,}")
        print(f"  Average journey length: {self.df.groupby('journey_id')['day_of_journey'].max().mean():.1f} days")
        
        print(f"\nJourney Outcomes:")
        resolution_counts = self.journey_summary['resolution_type'].value_counts()
        for resolution, count in resolution_counts.items():
            percentage = count / len(self.journey_summary) * 100
            print(f"  {resolution}: {count:,} ({percentage:.1f}%)")
        
        print(f"\nInfection Characteristics:")
        print(f"  Journeys with sepsis: {self.journey_summary['developed_sepsis'].sum():,} ({self.journey_summary['developed_sepsis'].mean()*100:.1f}%)")
        print(f"  Journeys with treatment: {self.journey_summary['was_treated'].sum():,} ({self.journey_summary['was_treated'].mean()*100:.1f}%)")
        print(f"  Hospital acquired infections: {self.journey_summary['hospital_acquired'].sum():,} ({self.journey_summary['hospital_acquired'].mean()*100:.1f}%)")
        
        print(f"\nMost Common Bacteria:")
        bacteria_counts = self.journey_summary['primary_bacteria'].value_counts().head(10)
        for bacteria, count in bacteria_counts.items():
            percentage = count / len(self.journey_summary) * 100
            print(f"  {bacteria.replace('_', ' ').title()}: {count:,} ({percentage:.1f}%)")
        
        print(f"\nDemographics:")
        print(f"  Average age at onset: {self.journey_summary['age_at_onset'].mean()/365.25:.1f} years")
        print(f"  Sex distribution:")
        sex_counts = self.journey_summary['sex'].value_counts()
        for sex, count in sex_counts.items():
            percentage = count / len(self.journey_summary) * 100
            print(f"    {sex.title()}: {count:,} ({percentage:.1f}%)")
        
        print(f"\nRegional Distribution:")
        region_counts = self.journey_summary['region'].value_counts()
        for region, count in region_counts.items():
            percentage = count / len(self.journey_summary) * 100
            print(f"  {region}: {count:,} ({percentage:.1f}%)")

def main():
    """Main function to run the analysis."""
    print("Infection Journey Analysis Tool")
    print("=" * 50)
    
    # Initialize analyzer
    analyzer = InfectionJourneyAnalyzer()
    
    # Generate summary report
    analyzer.generate_summary_report()
    
    # Generate detailed text report
    print(f"\nGenerating detailed text report for all journeys...")
    text_report_file = analyzer.generate_text_report()
    
    # Show available journey IDs for individual viewing
    print(f"\nAvailable journey IDs (showing first 20): {list(analyzer.df['journey_id'].unique()[:20])}")
    
    # Example individual journey analysis
    print(f"\nShowing example individual journey analysis...")
    analyzer.view_individual_journey(journey_id=analyzer.df['journey_id'].iloc[0])
    
    # Create population-level visualizations
    state_counts = analyzer.plot_infection_states_over_time(max_days=30)
    
    # Calculate mortality analysis
    mortality_analysis = analyzer.calculate_30_day_mortality()
    
    print(f"\nAnalysis complete! Files generated:")
    print(f"  📊 Figures: {analyzer.output_dir}/*.png")
    print(f"  📄 Text report: {text_report_file}")
    print(f"\nUse the following methods for further exploration:")
    print(f"  analyzer.view_individual_journey(journey_id=X)  # View specific journey")
    print(f"  analyzer.plot_infection_states_over_time()      # Population infection states")
    print(f"  analyzer.calculate_30_day_mortality()           # Mortality analysis")
    print(f"  analyzer.generate_text_report()                 # Generate detailed text report")
    
    return analyzer

if __name__ == "__main__":
    analyzer = main()