"""
Infection Journ# import seaborn as sns  # Commented out to avoid import issuesy Analysis Script

This script analyzes the infection_journeys.csv file generated by the AMR simulation
to provide insights into individual patient journeys and population-level outcomes.

Features:
1. View individual patient journeys with timeline visualization
2. Create stacked graphs of infection outcomes by day
3. Calculate 30-day mortality probability from infection onset
4. Summary statistics and outcome analysis

Author: Generated for AMR simulation analysis
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend for saving files only
import matplotlib.pyplot as plt
# import se                syndrome_name = self.syndrome_names.get(journey['syndrome'], f\"Syndrome {journey['syndrome']}\")\n                f.write(f\"Syndrome: {syndrome_name}\\n\")               syndrome_name = self.syndrome_names.get(journey['syndrome'], f\"Syndrome {journey['syndrome']}\")\n                f.write(f\"Syndrome: {syndrome_name}\\n\")born as sns  # Commented out to avoid import issues
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# =============================================================================
# CONFIGURATION SETTINGS - Modify these values as needed
# =============================================================================

# Number of individual journey timeline plots to generate
# Recommended range: 1-50 (higher numbers create more files)
# Files will be named: journey_01_timeline.png, journey_02_timeline.png, etc.
NUM_TIMELINE_PLOTS = 50

# Number of journeys to include in detailed text report
# Recommended range: 1-20 (higher numbers create much larger text files)
# Set to 0 to skip detailed report generation entirely
NUM_DETAILED_JOURNEYS = 50

# Enable verbose output during analysis
# True: Shows detailed progress messages and analysis results
# False: Silent operation (still generates all files)
VERBOSE_OUTPUT = False

# =============================================================================

class InfectionJourneyAnalyzer:
    def __init__(self, csv_file="infection_journeys.csv", output_dir="infection_journey_analysis_outputs", verbose=True):
        """Initialize the analyzer with the journey data."""
        self.verbose = verbose
        self.plot_counter = 0  # Counter for sequential plot numbering
        if self.verbose:
            print(f"Loading infection journey data from {csv_file}...")
        self.df = pd.read_csv(csv_file)
        self.output_dir = output_dir
        
        # Create output directory if it doesn't exist
        import os
        os.makedirs(output_dir, exist_ok=True)
        
        self.process_data()
        if self.verbose:
            print(f"Loaded {len(self.df)} journey snapshots for {self.df['journey_id'].nunique()} unique journeys")
            print(f"Figures will be saved to: {output_dir}")
        
    def process_data(self):
        """Process and clean the loaded data."""
        # Convert boolean columns
        bool_cols = ['sepsis', 'hospital_acquired', 'infection_identified', 'resistance_testing_done']
        for col in bool_cols:
            self.df[col] = self.df[col].astype(bool)
            
        # Create treatment status
        self.df['is_treated'] = self.df['current_drugs'].notna() & (self.df['current_drugs'] != "")
        
        # Create infection state categories
        self.df['infection_state'] = 'Unknown'
        self.df.loc[self.df['sepsis'] == True, 'infection_state'] = 'Sepsis'
        self.df.loc[(self.df['sepsis'] == False) & (self.df['is_treated'] == True), 'infection_state'] = 'Treated'
        self.df.loc[(self.df['sepsis'] == False) & (self.df['is_treated'] == False), 'infection_state'] = 'Not Treated'
        
        # Syndrome mapping (syndromes 1-10)
        self.syndrome_names = {
            1: "bloodstream infection",
            2: "pneumonia", 
            3: "urinary tract infection",
            4: "skin/soft tissue infection",
            5: "intra-abdominal infection",
            6: "central nervous system infection",
            7: "bone/joint infection",
            8: "endocarditis", 
            9: "surgical site infection",
            10: "other/unspecified infection"
        }
        
        # Process resolution types
        self.df['resolution_type'] = self.df['resolution_type'].fillna('Ongoing')
        
        # Create journey summaries
        self.journey_summary = self._create_journey_summary()
        
    def parse_drug_data(self, drug_string):
        """Parse drug data string into list of (drug_name, level) tuples."""
        if pd.isna(drug_string) or drug_string == "":
            return []
        
        drugs = []
        for item in drug_string.split(";"):
            if ":" in item:
                drug_name, level = item.split(":")
                drugs.append((drug_name.strip(), float(level)))
        return drugs
    
    def _create_journey_summary(self):
        """Create summary statistics for each journey."""
        summary_stats = []
        
        for journey_id in self.df['journey_id'].unique():
            journey_data = self.df[self.df['journey_id'] == journey_id].copy()
            journey_data = journey_data.sort_values('day_of_journey')
            
            summary = {
                'journey_id': journey_id,
                'individual_id': journey_data['individual_id'].iloc[0],
                'age_at_onset': journey_data['age_at_onset'].iloc[0],
                'sex': journey_data['sex'].iloc[0],
                'region': journey_data['region_living'].iloc[0],
                'primary_bacteria': journey_data['primary_bacteria'].iloc[0],
                'syndrome': journey_data['syndrome'].iloc[0],
                'immunodeficiency': journey_data['immunodeficiency'].iloc[0],
                'hospital_acquired': journey_data['hospital_acquired'].iloc[0],
                'duration_days': journey_data['day_of_journey'].max(),
                'max_bacteria_level': journey_data['primary_bacteria_level'].max(),
                'developed_sepsis': journey_data['sepsis'].any(),
                'was_treated': journey_data['is_treated'].any(),
                'treatment_failures': journey_data['treatment_failures'].max(),
                'resolution_type': self._determine_actual_resolution(journey_data),
                'died': self._determine_actual_resolution(journey_data) == 'Death',
                'died_within_30_days': (self._determine_actual_resolution(journey_data) == 'Death') and (journey_data['day_of_journey'].max() <= 30),
                'drug_selection_occurred': journey_data['drug_selection_bacteria'].notna().any(),
                'selected_drug': journey_data['selected_drug'].dropna().iloc[0] if journey_data['selected_drug'].notna().any() else None
            }
            summary_stats.append(summary)
            
        return pd.DataFrame(summary_stats)
    
    def view_individual_journey(self, journey_id=None, individual_id=None, sequential_number=None, highlight_de_novo=False):
        """View detailed timeline for a specific journey."""
        if journey_id is not None:
            journey_data = self.df[self.df['journey_id'] == journey_id].copy()
        elif individual_id is not None:
            journey_data = self.df[self.df['individual_id'] == individual_id].copy()
        else:
            # Show first available journey
            journey_data = self.df[self.df['journey_id'] == self.df['journey_id'].iloc[0]].copy()
            
        # Apply 90-day maximum journey length cap
        journey_data = journey_data[journey_data['day_of_journey'] <= 90].copy()
            
        if journey_data.empty:
            if self.verbose:
                print("No journey found with the specified criteria.")
            return
            
        journey_data = journey_data.sort_values('day_of_journey')
        journey_id = journey_data['journey_id'].iloc[0]
        individual_id = journey_data['individual_id'].iloc[0]
        
        if self.verbose:
            print(f"\n{'='*80}")
            print(f"INFECTION JOURNEY ANALYSIS - Journey ID: {journey_id}, Individual ID: {individual_id}")
            print(f"{'='*80}")
            
            # Patient demographics
            print(f"Patient Demographics:")
            print(f"  Age at onset: {journey_data['age_at_onset'].iloc[0]} days ({journey_data['age_at_onset'].iloc[0]/365.25:.1f} years)")
            print(f"  Sex: {journey_data['sex'].iloc[0]}")
            print(f"  Region: {journey_data['region_living'].iloc[0]}")
            print(f"  Immunodeficiency: {journey_data['immunodeficiency'].iloc[0]}")
            
            # Infection characteristics
            print(f"\nInfection Characteristics:")
            print(f"  Primary bacteria: {journey_data['primary_bacteria'].iloc[0]}")
            print(f"  Syndrome: {journey_data['syndrome'].iloc[0]}")
            print(f"  Hospital acquired: {journey_data['hospital_acquired'].iloc[0]}")
            print(f"  Journey duration: {journey_data['day_of_journey'].max()} days")
            print(f"  Final resolution: {journey_data['resolution_type'].iloc[-1]}")
        
        # Extend timeline 14 days after bacteria clearance if bacteria cleared
        bacteria_clearance_day = None
        bacteria_levels = journey_data['primary_bacteria_level'].values
        if len(bacteria_levels) > 0 and bacteria_levels[-1] <= 0.001:
            # Find first day bacteria was cleared
            cleared_indices = np.where(bacteria_levels <= 0.001)[0]
            if len(cleared_indices) > 0:
                bacteria_clearance_day = journey_data.iloc[cleared_indices[0]]['day_of_journey']
        
        # Note: The journey data already contains the actual drug levels as calculated 
        # by the Rust simulation with proper exponential decay. We don't need to extend
        # or recalculate drug levels - we should use the logged values directly.
        
        # Create timeline visualization
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 10))
        
        # Highlight de novo resistance cases in title
        title_prefix = "⭐ DE NOVO RESISTANCE ⭐ " if highlight_de_novo else ""
        fig.suptitle(f'{title_prefix}journey timeline - id: {journey_id}', fontsize=21, fontweight='bold')  # 14 * 1.5 = 21
        
        days = journey_data['day_of_journey']
        
        # Bacteria level over time with sepsis-aware coloring
        sepsis_status = journey_data['sepsis'].values
        bacteria_levels = journey_data['primary_bacteria_level'].values
        
        # Use step plot to show horizontal lines followed by vertical drops
        # This makes drug effects visually clear: level stays constant until drug acts, then drops immediately
        ax1.step(days, bacteria_levels, where='post', linewidth=4, color='blue', alpha=0.8)
            
        # Add markers with sepsis coloring
        sepsis_mask = sepsis_status
        no_sepsis_mask = ~sepsis_status
        if no_sepsis_mask.any():
            ax1.scatter(days[no_sepsis_mask], bacteria_levels[no_sepsis_mask], 
                       color='blue', marker='o', s=20, label='no sepsis', zorder=5)
        if sepsis_mask.any():
            ax1.scatter(days[sepsis_mask], bacteria_levels[sepsis_mask], 
                       color='red', marker='o', s=20, label='sepsis', zorder=5)
        
        # Get drug data for later use
        drug_data = self._parse_drug_and_resistance_data(journey_data)
        
        ax1.set_title('primary bacteria level', fontsize=18)  # Default ~12 * 1.5 = 18
        ax1.set_xlabel('day of journey', fontsize=15)  # 20 * 0.75 = 15
        ax1.set_ylabel('bacteria level', fontsize=15)
        ax1.set_xticks(range(1, int(days.max()) + 1))
        ax1.set_xlim(0.5, int(days.max()) + 0.5)
        ax1.set_ylim(bottom=0)  # Ensure y-axis starts at 0
        ax1.grid(True, alpha=0.3)
        if sepsis_mask.any():
            ax1.legend(fontsize=8)
        
        # Immunity and toxicity levels with step plotting
        ax2.step(days, journey_data['immunity_level'], where='post', color='green', linewidth=4, label='immunity', alpha=0.8)
        ax2.step(days, journey_data['toxicity_level'], where='post', color='red', linewidth=4, label='toxicity', alpha=0.8)
        ax2.set_title('immunity & toxicity levels', fontsize=18)
        ax2.set_xlabel('day of journey', fontsize=15)
        ax2.set_ylabel('level', fontsize=15)
        ax2.set_xticks(range(1, int(days.max()) + 1))
        ax2.set_xlim(0.5, int(days.max()) + 0.5)
        ax2.set_ylim(bottom=0)  # Ensure y-axis starts at 0
        ax2.legend()
        ax2.grid(True, alpha=0.3)
        
        # Drug levels and resistance (activity_r)
        # Note: drug_data already parsed above for markers
        
        if drug_data['has_drugs']:
            # Plot drug levels with vertical offset to prevent overlapping lines
            drug_colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']  # More distinct colors: blue, orange, green, red, purple
            
            # Collect all drug data first to detect overlaps
            drug_plot_data = []
            for i, (drug_name, drug_levels) in enumerate(drug_data['drug_levels'].items()):
                mask = ~pd.isna(drug_levels)
                if mask.any():
                    drug_plot_data.append({
                        'name': drug_name,
                        'levels': drug_levels[mask].copy(),
                        'days': days[mask],
                        'color': drug_colors[i % len(drug_colors)],
                        'index': i
                    })
            
            # Apply both vertical and horizontal offsets to prevent overlapping
            for drug_data_item in drug_plot_data:
                levels = drug_data_item['levels'].copy()
                days_original = drug_data_item['days']
                
                # Apply fixed y-axis offset to drug levels (same visual separation everywhere)
                # Use small fixed offsets: -0.15, +0.15, -0.3, +0.3, etc.
                drug_level_offset_magnitude = 0.15 * ((drug_data_item['index'] // 2) + 1)
                drug_level_offset_direction = 1 if drug_data_item['index'] % 2 == 0 else -1
                drug_level_offset = drug_level_offset_magnitude * drug_level_offset_direction
                
                # Apply larger x-axis offset: -0.3, +0.3, -0.6, +0.6 days, etc.
                x_offset_magnitude = 0.3 * ((drug_data_item['index'] // 2) + 1)
                x_offset_direction = 1 if drug_data_item['index'] % 2 == 0 else -1
                x_offset = x_offset_magnitude * x_offset_direction
                
                # Apply both offsets - use only fixed offset for consistent separation
                levels = levels + drug_level_offset
                days_offset = days_original + x_offset
                
                # Plot with y-axis offset applied to drug levels
                ax3.step(days_offset, levels, where='post', 
                        color=drug_data_item['color'], label=f"{drug_data_item['name']} level", 
                        linewidth=4, alpha=0.8)
            
            # Plot activity_r on secondary y-axis with matching colors and horizontal offsets
            ax3_twin = ax3.twinx()
            for i, (drug_name, activity_r) in enumerate(drug_data['activity_r'].items()):
                mask = ~pd.isna(activity_r)  # Show activity_r even when zero - removed (activity_r > 0) condition
                if mask.any():
                    # Use same color as corresponding drug level line
                    color = drug_colors[i % len(drug_colors)]
                    
                    # Apply same offsets as drug levels to keep them aligned and separated
                    x_offset_magnitude = 0.3 * ((i // 2) + 1)
                    x_offset_direction = 1 if i % 2 == 0 else -1
                    x_offset = x_offset_magnitude * x_offset_direction
                    days_offset_activity = days[mask] + x_offset
                    
                    # Apply very small y-axis offset to activity values, but ensure they don't go negative
                    original_activity_r = activity_r[mask]
                    
                    # Since Rust now only logs activity_r when both drug AND bacteria present,
                    # we can show all logged activity_r data (including zeros due to complete resistance)
                    activity_level_offset_magnitude = 0.002 * ((i // 2) + 1)  # Very small offset to avoid negative values
                    activity_level_offset_direction = 1 if i % 2 == 0 else -1
                    activity_level_offset = activity_level_offset_magnitude * activity_level_offset_direction
                    activity_r_offset = original_activity_r + activity_level_offset
                    
                    # Handle visibility: show positive values normally, but make zeros visible as tiny values
                    # This allows us to see when drugs are completely ineffective due to resistance
                    activity_r_offset = np.where(original_activity_r > 0.0,
                                               activity_r_offset.clip(lower=0.0001),  # Real values: ensure they stay positive
                                               np.full_like(activity_r_offset, 0.0001))  # Zeros: show as tiny but visible
                    
                    # Use stepped dashed lines with circle markers for each day, 1.5x thicker than drug levels (linewidth=4 * 1.5 = 6)
                    ax3_twin.step(days_offset_activity, activity_r_offset, where='post', color=color, linestyle='--',
                                 label=f'{drug_name} activity r', linewidth=6, alpha=0.8, zorder=10)
                    # Add circle markers for each day (with same offsets)
                    ax3_twin.plot(days_offset_activity, activity_r_offset, color=color, marker='o', 
                                 markersize=6, linestyle='', markerfacecolor='white', 
                                 markeredgecolor=color, markeredgewidth=2, zorder=11)
            
            ax3.set_xlabel('day of journey', fontsize=15)
            ax3.set_ylabel('drug level', fontsize=15)
            ax3_twin.set_ylabel('activity r', fontsize=15)
            ax3.set_title('drug and activity levels', fontsize=18)
            ax3.set_xticks(range(int(days.min()), int(days.max()) + 1))
            ax3.set_ylim(bottom=0)  # Ensure drug level y-axis starts at 0
            ax3_twin.set_ylim(0, 10)  # Standardized activity_r scale: base_potency(~1.0) × drug_level(max 10) × (1-resistance)
            ax3.grid(True, alpha=0.3)
            
            # Combine legends and place at top right
            lines1, labels1 = ax3.get_legend_handles_labels()
            lines2, labels2 = ax3_twin.get_legend_handles_labels()
            if lines1 or lines2:
                ax3.legend(lines1 + lines2, labels1 + labels2, loc='upper right', fontsize=8)
        else:
            ax3.text(0.5, 0.5, 'no drug treatment', transform=ax3.transAxes, 
                    ha='center', va='center', fontsize=12)
            ax3.set_title('drug and activity levels', fontsize=18)
            ax3.set_xlabel('day of journey', fontsize=15)
            ax3.set_xticks(range(1, int(days.max()) + 1))
            ax3.set_xlim(0.5, int(days.max()) + 0.5)
            ax3.set_ylim(bottom=0)  # Ensure y-axis starts at 0 even with no data
        
        # Clinical summary text (replacing hospital status plot)
        ax4.axis('off')  # Turn off axis for text display
        
        # Prepare clinical summary information
        # Calculate calendar year
        first_time_step = journey_data['time_step'].iloc[0]
        calendar_year = int(first_time_step / 365) + 1930
        
        # Find testing days
        bacteria_id_day = None
        if journey_data['infection_identified'].any():
            bacteria_id_day = journey_data[journey_data['infection_identified']]['day_of_journey'].min()
        
        resistance_test_day = None
        if journey_data['resistance_testing_done'].any():
            resistance_test_day = journey_data[journey_data['resistance_testing_done']]['day_of_journey'].min()
        
        sepsis_day = None
        if journey_data['sepsis'].any():
            sepsis_day = journey_data[journey_data['sepsis']]['day_of_journey'].min()
            
        # Find bacteria clearance day for duration calculation
        bacteria_clearance_day = None
        original_data = self.df[self.df['journey_id'] == journey_id].copy()  # Use original data without extension
        bacteria_levels = original_data['primary_bacteria_level'].values
        if len(bacteria_levels) > 0:
            cleared_indices = np.where(bacteria_levels <= 0.001)[0]
            if len(cleared_indices) > 0:
                bacteria_clearance_day = original_data.iloc[cleared_indices[0]]['day_of_journey']
        
        # Get drug potency and resistance information
        drug_potency_info = self._get_drug_potency_resistance_info(original_data)
        
        # Get drug failure day information
        drug_failure_info = self._get_drug_failure_info(original_data)
        
        # Get other bacteria present during journey
        other_bacteria_info = self._get_other_bacteria_info(original_data)
        
        death_day = None
        death_cause = journey_data['resolution_type'].iloc[-1]
        is_death = False
        
        # Check for death resolution types
        if pd.notna(death_cause) and ('Death' in str(death_cause)):
            is_death = True
            death_day = journey_data['day_of_journey'].max()
        
        # Check if journey is ongoing (NaN resolution)
        is_ongoing = pd.isna(death_cause) or death_cause == ''
        
        # Format clinical information
        if is_ongoing:
            outcome_text = f"ongoing ({journey_data['day_of_journey'].max()} days)"
        elif is_death:
            outcome_text = f"died day {death_day} ({death_cause})"
        else:
            outcome_text = f"recovered ({death_cause})"
        
        # Get syndrome name
        syndrome_num = journey_data['syndrome'].iloc[0]
        syndrome_name = self.syndrome_names.get(syndrome_num, f"syndrome {syndrome_num}")
        
        # Calculate duration as time to bacteria clearance
        if bacteria_clearance_day is not None:
            duration_text = f"{bacteria_clearance_day} days (to clearance)"
        else:
            duration_text = f"{original_data['day_of_journey'].max()} days (ongoing)"
        
        # Check for de novo resistance status
        has_de_novo = False
        if 'has_de_novo_resistance' in journey_data.columns:
            has_de_novo = journey_data['has_de_novo_resistance'].any()
        
        # Get resistance source information for de novo cases
        resistance_sources_info = []
        if has_de_novo and 'resistance_sources' in journey_data.columns:
            resistance_sources_info = self._get_resistance_sources_info(journey_data)
        
        clinical_info = [
            f"year: {calendar_year}",
            f"bacteria: {journey_data['primary_bacteria'].iloc[0]}",
            f"region: {journey_data['region_living'].iloc[0]}",
            f"age: {journey_data['age_at_onset'].iloc[0]/365.25:.1f} years",
            f"syndrome: {syndrome_name}",
            f"sepsis: {'day ' + str(sepsis_day) if sepsis_day else 'none'}",
            f"bacteria identified: {'day ' + str(bacteria_id_day) if bacteria_id_day else 'no'}",
            f"resistance test: {'day ' + str(resistance_test_day) if resistance_test_day else 'no'}",
            f"⭐ de novo resistance: {'yes' if has_de_novo else 'no'}",
            f"outcome: {outcome_text}",
            f"duration: {duration_text}",
            f"hospital acquired: {'yes' if journey_data['hospital_acquired'].iloc[0] else 'no'}"
        ]
        
        # Add resistance source information for de novo cases
        if resistance_sources_info:
            clinical_info.extend(resistance_sources_info)
            
        # Add drug potency and resistance information
        if drug_potency_info:
            clinical_info.extend(drug_potency_info)
            
        # Add drug failure information
        if drug_failure_info:
            clinical_info.extend(drug_failure_info)
            
        # Add other bacteria information
        if other_bacteria_info:
            clinical_info.extend(other_bacteria_info)
        
        # Display clinical information as text with reduced vertical spacing
        # Position title at same level as drug plot title, use larger fonts
        ax4.text(0.05, 1.02, "clinical summary", transform=ax4.transAxes, 
                fontsize=18, fontweight='bold', va='top')  # Match drug plot title level
        
        # Reduce line spacing and use Calibri font with smaller size for items
        for i, info in enumerate(clinical_info):
            ax4.text(0.05, 0.89 - i*0.05, info, transform=ax4.transAxes, 
                    fontsize=12, va='top', family='Calibri')  # Reduced from 15 to 12, Calibri font
        
        plt.tight_layout()
        
        # Save the figure with sequential numbering
        if sequential_number is not None:
            filename = f"journey_{sequential_number:02d}_timeline.png"
        else:
            # Auto-increment counter if no specific number provided
            self.plot_counter += 1
            filename = f"journey_{self.plot_counter:02d}_timeline.png"
        filepath = f"{self.output_dir}/{filename}"
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        if self.verbose:
            print(f"Saved individual journey plot: {filepath}")
        
        plt.close()  # Close figure to free memory
        
        # Print detailed day-by-day progression
        if self.verbose:
            print(f"\nDay-by-Day Progression:")
            print(f"{'Day':>3} {'Bacteria':>8} {'Immunity':>8} {'Toxicity':>8} {'Treated':>7} {'Sepsis':>6} {'Hospital':>10}")
            print("-" * 65)
            
            for _, row in journey_data.iterrows():
                treated = 'Yes' if row['is_treated'] else 'No'
                sepsis = 'Yes' if row['sepsis'] else 'No'
                print(f"{row['day_of_journey']:>3} {row['primary_bacteria_level']:>8.3f} {row['immunity_level']:>8.3f} "
                      f"{row['toxicity_level']:>8.3f} {treated:>7} {sepsis:>6} {row['hospital_status']:>10}")
    
    def plot_infection_states_over_time(self, max_days=30):
        """Create stacked bar chart of infection states by day."""
        if self.verbose:
            print(f"\nCreating infection states visualization (first {max_days} days)...")
        
        # Filter to first N days for readability
        daily_data = self.df[self.df['day_of_journey'] <= max_days].copy()
        
        # Count states by day
        state_counts = daily_data.groupby(['day_of_journey', 'infection_state']).size().unstack(fill_value=0)
        
        # Create stacked bar chart
        fig, ax = plt.subplots(figsize=(14, 8))
        
        colors = {'Not Treated': '#FF6B6B', 'Treated': '#4ECDC4', 'Sepsis': '#45B7D1', 'Unknown': '#96CEB4'}
        state_counts.plot(kind='bar', stacked=True, ax=ax, color=[colors.get(col, '#95A5A6') for col in state_counts.columns])
        
        ax.set_title(f'Infection States Over Time (First {max_days} Days)', fontsize=14, fontweight='bold')
        ax.set_xlabel('Day of Journey')
        ax.set_ylabel('Number of Individuals')
        ax.legend(title='Infection State', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.grid(True, alpha=0.3, axis='y')
        
        # Set x-axis to show whole days
        day_range = range(1, max_days + 1)
        ax.set_xticks(range(len(state_counts.index)))
        ax.set_xticklabels([str(day) for day in state_counts.index])
        plt.xticks(rotation=45)
        plt.tight_layout()
        
        # Save the figure
        filename = f"infection_states_stacked_first_{max_days}_days.png"
        filepath = f"{self.output_dir}/{filename}"
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        if self.verbose:
            print(f"Saved infection states plot: {filepath}")
        
        plt.close()  # Close figure to free memory
        
        return state_counts
    
    def calculate_30_day_mortality(self):
        """Calculate and visualize 30-day mortality probability."""
        if self.verbose:
            print("\nCalculating 30-day mortality analysis...")
        
        # Filter journeys that either died within 30 days or survived at least 30 days
        mortality_analysis = []
        
        for journey_id in self.journey_summary['journey_id'].unique():
            journey_info = self.journey_summary[self.journey_summary['journey_id'] == journey_id].iloc[0]
            
            # Include if journey lasted at least 30 days OR ended in death
            if journey_info['duration_days'] >= 30 or journey_info['died']:
                mortality_analysis.append({
                    'journey_id': journey_id,
                    'died_within_30_days': journey_info['died_within_30_days'],
                    'duration_days': min(journey_info['duration_days'], 30),
                    'age_at_onset': journey_info['age_at_onset'],
                    'sex': journey_info['sex'],
                    'primary_bacteria': journey_info['primary_bacteria'],
                    'developed_sepsis': journey_info['developed_sepsis'],
                    'was_treated': journey_info['was_treated']
                })
        
        mortality_df = pd.DataFrame(mortality_analysis)
        
        if len(mortality_df) == 0:
            if self.verbose:
                print("No journeys available for 30-day mortality analysis.")
            return None
        
        # Calculate overall 30-day mortality rate
        overall_mortality = mortality_df['died_within_30_days'].mean()
        if self.verbose:
            print(f"Overall 30-day mortality rate: {overall_mortality:.1%} ({mortality_df['died_within_30_days'].sum()}/{len(mortality_df)} cases)")
        
        # Create mortality analysis plots
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 10))
        fig.suptitle('30-Day Mortality Analysis', fontsize=14, fontweight='bold')
        
        # Mortality by bacteria type
        bacteria_mortality = mortality_df.groupby('primary_bacteria')['died_within_30_days'].agg(['count', 'sum', 'mean']).reset_index()
        bacteria_mortality = bacteria_mortality[bacteria_mortality['count'] >= 5]  # At least 5 cases
        bacteria_mortality = bacteria_mortality.sort_values('mean', ascending=True)
        
        if len(bacteria_mortality) > 0:
            ax1.barh(range(len(bacteria_mortality)), bacteria_mortality['mean'], color='crimson', alpha=0.7)
            ax1.set_yticks(range(len(bacteria_mortality)))
            ax1.set_yticklabels([name.replace('_', ' ').title() for name in bacteria_mortality['primary_bacteria']])
            ax1.set_xlabel('30-Day Mortality Rate')
            ax1.set_title('Mortality by Bacteria Type')
            ax1.grid(True, alpha=0.3, axis='x')
        
        # Mortality by sepsis development
        sepsis_mortality = mortality_df.groupby('developed_sepsis')['died_within_30_days'].mean()
        ax2.bar(['No Sepsis', 'Developed Sepsis'], sepsis_mortality.values, color=['lightblue', 'darkred'], alpha=0.7)
        ax2.set_ylabel('30-Day Mortality Rate')
        ax2.set_title('Mortality by Sepsis Development')
        ax2.grid(True, alpha=0.3, axis='y')
        
        # Mortality by treatment status
        treatment_mortality = mortality_df.groupby('was_treated')['died_within_30_days'].mean()
        ax3.bar(['Not Treated', 'Treated'], treatment_mortality.values, color=['orange', 'green'], alpha=0.7)
        ax3.set_ylabel('30-Day Mortality Rate')
        ax3.set_title('Mortality by Treatment Status')
        ax3.grid(True, alpha=0.3, axis='y')
        
        # Age distribution of deaths vs survivors
        died_ages = mortality_df[mortality_df['died_within_30_days']]['age_at_onset'] / 365.25
        survived_ages = mortality_df[~mortality_df['died_within_30_days']]['age_at_onset'] / 365.25
        
        ax4.hist([died_ages, survived_ages], bins=20, alpha=0.7, label=['Died', 'Survived'], color=['red', 'blue'])
        ax4.set_xlabel('Age at Onset (years)')
        ax4.set_ylabel('Frequency')
        ax4.set_title('Age Distribution: Deaths vs Survivors')
        ax4.legend()
        ax4.grid(True, alpha=0.3, axis='y')
        
        plt.tight_layout()
        
        # Save the figure
        filename = "30_day_mortality_analysis.png"
        filepath = f"{self.output_dir}/{filename}"
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        if self.verbose:
            print(f"Saved mortality analysis plot: {filepath}")
        
        plt.close()  # Close figure to free memory
        
        return mortality_df
    
    def detect_death_day(self, journey_data):
        """Detect the day when death likely occurred based on static values"""
        if len(journey_data) < 10:  # Need sufficient data points
            return None
            
        # Look for patterns indicating death (static values for extended periods)
        for start_idx in range(5, len(journey_data) - 5):  # Start checking after day 5
            current_row = journey_data.iloc[start_idx]
            
            # Check if the next 5+ days have identical values (indicating death/simulation stop)
            static_count = 0
            for check_idx in range(start_idx, min(start_idx + 10, len(journey_data))):
                check_row = journey_data.iloc[check_idx]
                
                # Check if key values are identical (indicating simulation stopped)
                if (abs(check_row['primary_bacteria_level'] - current_row['primary_bacteria_level']) < 0.001 and
                    abs(check_row['immunity_level'] - current_row['immunity_level']) < 0.001 and
                    abs(check_row['toxicity_level'] - current_row['toxicity_level']) < 0.001 and
                    check_row['sepsis'] == current_row['sepsis'] and
                    check_row['is_treated'] == current_row['is_treated']):
                    static_count += 1
                else:
                    break
            
            # If we found 5+ consecutive identical days, death likely occurred
            if static_count >= 5:
                return current_row['day_of_journey']
        
        return None
    
    def determine_death_cause(self, death_row):
        """Determine the likely cause of death based on final state"""
        causes = []
        
        # High toxicity death
        if death_row['toxicity_level'] > 3.5:
            causes.append("Toxicity")
        
        # Sepsis death
        if death_row['sepsis']:
            causes.append("Sepsis")
        
        # Severe infection death
        if death_row['primary_bacteria_level'] > 3.0:
            causes.append("Severe infection")
        
        # Default if no clear cause identified
        if not causes:
            causes.append("Multi-organ failure")
        
        return " + ".join(causes)
    
    def _parse_drug_and_resistance_data(self, journey_data):
        """Parse drug levels and resistance data from journey data"""
        drug_data = {
            'has_drugs': False,
            'drug_levels': {},
            'activity_r': {}
        }
        
        # Check if there are any drugs in this journey
        has_treatment = journey_data['current_drugs'].notna() & (journey_data['current_drugs'] != "")
        if not has_treatment.any():
            return drug_data
        
        drug_data['has_drugs'] = True
        
        # Parse current_drugs field to extract drug names and levels
        for _, row in journey_data.iterrows():
            if pd.isna(row['current_drugs']) or row['current_drugs'] == "":
                continue
                
            # Parse drug string format: "drug1:level1;drug2:level2"
            drugs_str = row['current_drugs']
            if drugs_str and isinstance(drugs_str, str):
                for drug_entry in drugs_str.split(';'):
                    if ':' in drug_entry:
                        drug_name, level_str = drug_entry.split(':', 1)
                        drug_name = drug_name.strip()
                        try:
                            level = float(level_str.strip())
                            if drug_name not in drug_data['drug_levels']:
                                drug_data['drug_levels'][drug_name] = pd.Series(index=journey_data.index, dtype=float)
                            drug_data['drug_levels'][drug_name].loc[row.name] = level
                        except ValueError:
                            continue
        
        # Parse resistance_activity_r field  
        for _, row in journey_data.iterrows():
            if pd.isna(row['resistance_activity_r']) or row['resistance_activity_r'] == "":
                continue
                
            # Parse resistance string format: "drug1:value1;drug2:value2"
            resistance_str = row['resistance_activity_r']
            if resistance_str and isinstance(resistance_str, str):
                for resistance_entry in resistance_str.split(';'):
                    if ':' in resistance_entry:
                        drug_name, value_str = resistance_entry.split(':', 1)
                        drug_name = drug_name.strip()
                        try:
                            value = float(value_str.strip())
                            if drug_name not in drug_data['activity_r']:
                                drug_data['activity_r'][drug_name] = pd.Series(index=journey_data.index, dtype=float)
                            drug_data['activity_r'][drug_name].loc[row.name] = value
                        except ValueError:
                            continue
        
        return drug_data
    
    def _determine_actual_resolution(self, journey_data):
        """Determine the actual resolution based on the data"""
        final_resolution = journey_data['resolution_type'].iloc[-1]
        
        # If resolution is NaN or empty, it's an ongoing journey
        if pd.isna(final_resolution) or final_resolution == '':
            return 'Ongoing'
        
        # Otherwise use the resolution from the data
        return final_resolution
    
    def generate_text_report(self):
        """Generate comprehensive text report file with detailed journey listings."""
        filename = f"{self.output_dir}/infection_journeys_detailed_report.txt"
        
        with open(filename, 'w') as f:
            # Write header
            f.write("="*80 + "\n")
            f.write("DETAILED INFECTION JOURNEY ANALYSIS REPORT\n")
            f.write("="*80 + "\n")
            f.write(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Total journeys: {len(self.journey_summary)}\n")
            f.write(f"Total snapshots: {len(self.df):,}\n\n")
            
            # Summary statistics
            f.write("SUMMARY STATISTICS\n")
            f.write("-" * 40 + "\n")
            f.write(f"Average journey length: {self.df.groupby('journey_id')['day_of_journey'].max().mean():.1f} days\n")
            f.write(f"Journeys with sepsis: {self.journey_summary['developed_sepsis'].sum()} ({self.journey_summary['developed_sepsis'].mean()*100:.1f}%)\n")
            f.write(f"Journeys with treatment: {self.journey_summary['was_treated'].sum()} ({self.journey_summary['was_treated'].mean()*100:.1f}%)\n")
            f.write(f"Journeys with drug selection events: {self.journey_summary['drug_selection_occurred'].sum()}\n")
            f.write(f"Hospital acquired infections: {self.journey_summary['hospital_acquired'].sum()} ({self.journey_summary['hospital_acquired'].mean()*100:.1f}%)\n\n")
            
            # Resolution type breakdown
            f.write("JOURNEY OUTCOMES\n")
            f.write("-" * 40 + "\n")
            resolution_counts = self.journey_summary['resolution_type'].value_counts()
            for resolution, count in resolution_counts.items():
                percentage = count / len(self.journey_summary) * 100
                f.write(f"  {resolution}: {count:,} ({percentage:.1f}%)\n")
            f.write("\n")
            
            # Bacteria breakdown
            f.write("BACTERIA DISTRIBUTION\n")
            f.write("-" * 40 + "\n")
            bacteria_counts = self.journey_summary['primary_bacteria'].value_counts().head(15)
            for bacteria, count in bacteria_counts.items():
                percentage = count / len(self.journey_summary) * 100
                f.write(f"  {bacteria.replace('_', ' ').title()}: {count:,} ({percentage:.1f}%)\n")
            f.write("\n")
            
            # Detailed individual journey listings
            f.write("="*80 + "\n")
            f.write("DETAILED INDIVIDUAL JOURNEY LISTINGS\n")
            f.write("="*80 + "\n\n")
            
            # Sort journeys by ID for consistent ordering
            journeys_to_process = self.journey_summary.sort_values('journey_id').head(NUM_DETAILED_JOURNEYS)
            f.write(f"Showing detailed analysis for first {NUM_DETAILED_JOURNEYS} journeys (out of {len(self.journey_summary)} total)\n\n")
            
            for idx, (_, journey) in enumerate(journeys_to_process.iterrows(), 1):
                journey_id = journey['journey_id']
                journey_data = self.df[self.df['journey_id'] == journey_id].copy()
                journey_data = journey_data.sort_values('day_of_journey')
                
                f.write(f"JOURNEY #{idx} (ID: {journey_id})\n")
                f.write("-" * 60 + "\n")
                
                # Calculate calendar year from time_step
                first_time_step = journey_data['time_step'].iloc[0]
                calendar_year = int(first_time_step / 365) + 1930
                
                # Patient demographics
                f.write(f"Patient ID: {journey['individual_id']}\n")
                f.write(f"Calendar year: {calendar_year}\n")
                f.write(f"Age at onset: {journey['age_at_onset']} days ({journey['age_at_onset']/365.25:.1f} years)\n")
                f.write(f"Sex: {journey['sex']}\n")
                f.write(f"Region: {journey['region']}\n")
                f.write(f"Immunodeficiency: {journey['immunodeficiency']}\n\n")
                
                # Infection characteristics
                f.write(f"Primary bacteria: {journey['primary_bacteria'].replace('_', ' ').title()}\n")
                syndrome_name = self.syndrome_names.get(journey['syndrome'], f"Syndrome {journey['syndrome']}")
                f.write(f"Syndrome: {syndrome_name}\n")
                f.write(f"Hospital acquired: {journey['hospital_acquired']}\n")
                f.write(f"Journey duration: {journey['duration_days']} days\n")
                f.write(f"Maximum bacteria level: {journey['max_bacteria_level']:.3f}\n")
                f.write(f"Developed sepsis: {journey['developed_sepsis']}\n")
                f.write(f"Received treatment: {journey['was_treated']}\n")
                f.write(f"Treatment failures: {journey['treatment_failures']}\n")
                
                # Add other bacteria present during journey
                other_bacteria_info = self._get_other_bacteria_info(journey_data)
                if other_bacteria_info:
                    for info_line in other_bacteria_info:
                        if info_line.strip():  # Skip empty lines
                            f.write(f"{info_line}\n")
                    f.write("\n")
                
                # Add testing information
                bacteria_id_day = None
                if journey_data['infection_identified'].any():
                    bacteria_id_day = journey_data[journey_data['infection_identified']]['day_of_journey'].min()
                
                resistance_test_day = None
                if journey_data['resistance_testing_done'].any():
                    resistance_test_day = journey_data[journey_data['resistance_testing_done']]['day_of_journey'].min()
                
                f.write(f"Bacteria identified: {'Day ' + str(bacteria_id_day) if bacteria_id_day else 'Not identified'}\n")
                f.write(f"Resistance testing: {'Day ' + str(resistance_test_day) if resistance_test_day else 'Not performed'}\n")
                if journey['drug_selection_occurred']:
                    f.write(f"Selected drug: {journey['selected_drug']}\n")
                else:
                    f.write(f"No drug selection recorded\n")
                # Show corrected resolution (detect death if present)
                actual_resolution = self._determine_actual_resolution(journey_data)
                if actual_resolution != journey['resolution_type']:
                    f.write(f"Final resolution: {actual_resolution} (originally recorded as: {journey['resolution_type']})\n\n")
                else:
                    f.write(f"Final resolution: {actual_resolution}\n\n")
                
                # Drug selection information if available (only show meaningful selections)
                drug_selection_data = journey_data[journey_data['drug_selection_bacteria'].notna()]
                if not drug_selection_data.empty:
                    f.write("Drug Selection Information:\n")
                    displayed_selections = set()
                    for _, selection_row in drug_selection_data.iterrows():
                        # Parse drug scores to see if this is a meaningful selection
                        scores = self.parse_drug_data(selection_row['drug_selection_scores'])
                        has_selected_drug = pd.notna(selection_row['selected_drug']) and selection_row['selected_drug'] != ""
                        
                        # Only show if we have scores or a selected drug, and haven't shown this selection already
                        selection_key = (selection_row['day_of_journey'], selection_row['drug_selection_bacteria'])
                        if (scores or has_selected_drug) and selection_key not in displayed_selections:
                            displayed_selections.add(selection_key)
                            f.write(f"Day {selection_row['day_of_journey']}: Drug selection for {selection_row['drug_selection_bacteria']}\n")
                            
                            if scores:
                                f.write("  Drug scores at selection time:\n")
                                # Sort by score (highest first)
                                scores.sort(key=lambda x: x[1], reverse=True)
                                for drug_name, score in scores:
                                    f.write(f"    {drug_name}: {score:.4f}\n")
                            
                            if has_selected_drug:
                                f.write(f"  Selected drug: {selection_row['selected_drug']}\n")
                            f.write("\n")
                
                # Day-by-day progression (show ALL days until death)
                f.write("Day-by-day progression:\n")
                f.write("day | bacteria | immunity | toxicity | drugs (level)        | majority_r | activity_r | sepsis | hospital    | death                 | notes\n")
                f.write("-" * 165 + "\n")
                
                # Identify key milestone days for annotations
                treatment_starts = journey_data[journey_data['is_treated'] & ~journey_data['is_treated'].shift(1, fill_value=False)]
                sepsis_starts = journey_data[journey_data['sepsis'] & ~journey_data['sepsis'].shift(1, fill_value=False)]
                hospital_changes = journey_data[journey_data['hospital_status'] != journey_data['hospital_status'].shift(1, fill_value='')]
                
                treatment_start_days = set(treatment_starts['day_of_journey'].tolist())
                sepsis_start_days = set(sepsis_starts['day_of_journey'].tolist())
                hospital_change_days = set(hospital_changes['day_of_journey'].tolist())
                
                # Detect death by looking for static values (indicating simulation stopped processing)
                death_day = self.detect_death_day(journey_data)
                
                # Show days until death (or all days if no death detected)
                last_day_to_show = death_day if death_day else journey_data['day_of_journey'].max()
                
                try:
                    for _, row in journey_data.iterrows():
                        day = row['day_of_journey']
                        
                        # Stop showing days after death
                        if death_day and day > death_day:
                            break
                            
                        # Parse current drugs and levels
                        current_drugs = self.parse_drug_data(row['current_drugs'])
                        if current_drugs:
                            # Show up to 3 drugs with their actual levels
                            drug_entries = []
                            for drug, level in current_drugs[:3]:
                                drug_entries.append(f"{drug}({level:.1f})")
                            drug_str = ", ".join(drug_entries)
                            if len(current_drugs) > 3:
                                drug_str += f" +{len(current_drugs)-3}more"
                        else:
                            drug_str = "none"
                        drug_str = f"{drug_str:<20}"  # Fixed width for alignment
                        
                        # Parse resistance data for current drugs
                        majority_r_data = self.parse_drug_data(row['resistance_majority_r'])
                        activity_r_data = self.parse_drug_data(row['resistance_activity_r'])
                        
                        # Get resistance levels for current drugs
                        maj_r_levels = []
                        act_r_levels = []
                        for drug_name, _ in current_drugs:
                            # Find resistance for this drug
                            maj_r = next((level for drug, level in majority_r_data if drug == drug_name), 0.0)
                            act_r = next((level for drug, level in activity_r_data if drug == drug_name), 0.0)
                            maj_r_levels.append(maj_r)
                            act_r_levels.append(act_r)
                        
                        maj_r_str = f"{max(maj_r_levels):.2f}" if maj_r_levels else "0.00"
                        act_r_str = f"{max(act_r_levels):.2f}" if act_r_levels else "0.00"
                        
                        sepsis = 'yes' if row['sepsis'] else 'no'
                        
                        # Determine death status and cause
                        death_status = "no"
                        death_cause = ""
                        
                        # Check for death from resolution_type
                        resolution_type = row['resolution_type']
                        if pd.notna(resolution_type) and 'Death' in str(resolution_type):
                            death_status = f"yes ({resolution_type})"
                        elif death_day and day == death_day:
                            death_status = "yes"
                            death_cause = self.determine_death_cause(row)
                        
                        # Add notes for key events
                        notes = []
                        if day in treatment_start_days:
                            # Add specific drug name when treatment starts
                            if current_drugs:
                                drug_names = [drug for drug, _ in current_drugs]
                                notes.append(f"started: {', '.join(drug_names)}")
                            else:
                                notes.append("treatment started")
                        if day in sepsis_start_days:
                            notes.append("sepsis onset")
                        if day in hospital_change_days:
                            notes.append(f"hospital: {row['hospital_status']}")
                        if death_cause:
                            notes.append(f"death: {death_cause}")
                        
                        note_str = "; ".join(notes) if notes else ""
                        
                        f.write(f"{day:3d} | {row['primary_bacteria_level']:8.3f} | {row['immunity_level']:8.3f} | "
                               f"{row['toxicity_level']:8.3f} | {drug_str} | {maj_r_str:10} | {act_r_str:10} | {sepsis.lower():6} | "
                               f"{row['hospital_status']:11} | {death_status:21} | {note_str}\n")
                except KeyboardInterrupt:
                    f.write(f"\n*** PROCESSING INTERRUPTED for Journey {journey_id} ***\n")
                    print(f"Processing interrupted for journey {journey_id}")
                    break
                except Exception as e:
                    f.write(f"\n*** ERROR PROCESSING Journey {journey_id}: {str(e)} ***\n")
                    print(f"Error processing journey {journey_id}: {str(e)}")
                    continue                # Add summary if death was detected
                if death_day:
                    f.write(f"\n*** DEATH DETECTED ON DAY {death_day} - Journey terminated ***\n")
                
                f.write("\n" + "="*80 + "\n\n")
        
        if self.verbose:
            print(f"Detailed text report saved: {filename}")
        return filename

    def generate_summary_report(self):
        """Generate comprehensive summary report."""
        if self.verbose:
            print(f"\n{'='*80}")
            print("INFECTION JOURNEY ANALYSIS SUMMARY REPORT")
            print(f"{'='*80}")
            print(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            
            print(f"\nDataset Overview:")
            print(f"  Total journey snapshots: {len(self.df):,}")
            print(f"  Unique journeys: {self.df['journey_id'].nunique():,}")
            print(f"  Unique individuals: {self.df['individual_id'].nunique():,}")
            print(f"  Average journey length: {self.df.groupby('journey_id')['day_of_journey'].max().mean():.1f} days")
            
            print(f"\nJourney Outcomes:")
            resolution_counts = self.journey_summary['resolution_type'].value_counts()
            for resolution, count in resolution_counts.items():
                percentage = count / len(self.journey_summary) * 100
                print(f"  {resolution}: {count:,} ({percentage:.1f}%)")
            
            print(f"\nInfection Characteristics:")
            print(f"  Journeys with sepsis: {self.journey_summary['developed_sepsis'].sum():,} ({self.journey_summary['developed_sepsis'].mean()*100:.1f}%)")
            print(f"  Journeys with treatment: {self.journey_summary['was_treated'].sum():,} ({self.journey_summary['was_treated'].mean()*100:.1f}%)")
            print(f"  Hospital acquired infections: {self.journey_summary['hospital_acquired'].sum():,} ({self.journey_summary['hospital_acquired'].mean()*100:.1f}%)")
            
            print(f"\nMost Common Bacteria:")
            bacteria_counts = self.journey_summary['primary_bacteria'].value_counts().head(10)
            for bacteria, count in bacteria_counts.items():
                percentage = count / len(self.journey_summary) * 100
                print(f"  {bacteria.replace('_', ' ').title()}: {count:,} ({percentage:.1f}%)")
            
            print(f"\nDemographics:")
            print(f"  Average age at onset: {self.journey_summary['age_at_onset'].mean()/365.25:.1f} years")
            print(f"  Sex distribution:")
            sex_counts = self.journey_summary['sex'].value_counts()
            for sex, count in sex_counts.items():
                percentage = count / len(self.journey_summary) * 100
                print(f"    {sex.title()}: {count:,} ({percentage:.1f}%)")
            
            print(f"\nRegional Distribution:")
            region_counts = self.journey_summary['region'].value_counts()
            for region, count in region_counts.items():
                percentage = count / len(self.journey_summary) * 100
                print(f"  {region}: {count:,} ({percentage:.1f}%)")
    
    def _get_drug_potency_resistance_info(self, journey_data):
        """Extract drug potency and any_r resistance values on the day each drug was started."""
        drug_info = []
        
        # Find all drugs used and their start days
        drug_start_info = {}
        
        for _, row in journey_data.iterrows():
            if pd.notna(row['current_drugs']) and row['current_drugs'] != '':
                drug_entries = row['current_drugs'].split(';')
                day = int(row['day_of_journey'])
                
                for entry in drug_entries:
                    if ':' in entry:
                        drug_name, level_str = entry.split(':', 1)
                        try:
                            level = float(level_str)
                            if level > 0.1:  # Only consider significant drug levels
                                # Track the earliest day this drug appeared
                                if drug_name not in drug_start_info or day < drug_start_info[drug_name]['start_day']:
                                    drug_start_info[drug_name] = {
                                        'start_day': day,
                                        'potency': level,
                                        'row_data': row
                                    }
                        except ValueError:
                            continue
        
        if drug_start_info:
            drug_info.append("")  # Add spacing
            
            # For each drug, get potency and any_r on start day
            for drug_name in sorted(drug_start_info.keys()):
                start_info = drug_start_info[drug_name]
                potency = start_info['potency']
                start_row = start_info['row_data']
                
                # Find any_r resistance value on drug start day
                any_r_value = None
                if pd.notna(start_row['resistance_any_r']) and start_row['resistance_any_r'] != '':
                    any_r_entries = start_row['resistance_any_r'].split(';')
                    for entry in any_r_entries:
                        if ':' in entry and entry.startswith(drug_name + ':'):
                            _, level_str = entry.split(':', 1)
                            try:
                                any_r_value = float(level_str)
                                break
                            except ValueError:
                                continue
                
                # Format the drug information
                if any_r_value is not None:
                    drug_info.append(f"potency: {potency:.1f} {drug_name}: any_r: {any_r_value:.3f}")
                else:
                    drug_info.append(f"potency: {potency:.1f} {drug_name}: any_r: no data")
        
        return drug_info
    
    def _get_other_bacteria_info(self, journey_data):
        """Extract information about other bacteria present during the journey."""
        other_bacteria_info = []
        
        # Get primary bacteria to exclude it
        primary_bacteria = journey_data['primary_bacteria'].iloc[0]
        
        # Find rows with other bacteria levels
        other_bacteria_found = {}
        
        for _, row in journey_data.iterrows():
            if pd.notna(row['all_bacteria_levels']) and row['all_bacteria_levels'] != '':
                bacteria_entries = row['all_bacteria_levels'].split(';')
                day = int(row['day_of_journey'])
                
                for entry in bacteria_entries:
                    if ':' in entry:
                        bacteria_name, level_str = entry.split(':', 1)
                        try:
                            level = float(level_str)
                            if bacteria_name != primary_bacteria and level > 0.001:
                                if bacteria_name not in other_bacteria_found:
                                    other_bacteria_found[bacteria_name] = day
                                else:
                                    # Keep the earliest appearance
                                    other_bacteria_found[bacteria_name] = min(other_bacteria_found[bacteria_name], day)
                        except ValueError:
                            continue
        
        if other_bacteria_found:
            other_bacteria_info.append("")  # Add spacing
            other_bacteria_info.append("Other bacteria present:")
            
            # Sort by first appearance day
            sorted_bacteria = sorted(other_bacteria_found.items(), key=lambda x: x[1])
            for bacteria_name, first_day in sorted_bacteria:
                other_bacteria_info.append(f"  {bacteria_name}: Day {first_day}")
        
        return other_bacteria_info
    
    def _get_drug_failure_info(self, journey_data):
        """Extract drug failure event information from the journey data."""
        drug_failure_info = []
        
        # Look for treatment failure events in the journey
        failure_days = []
        
        for _, row in journey_data.iterrows():
            # Check if treatment_failures increased on this day
            treatment_failures = row['treatment_failures']
            if pd.notna(treatment_failures) and treatment_failures > 0:
                day = int(row['day_of_journey'])
                
                # Check if this is a new failure (compare with previous day if available)
                is_new_failure = True
                if day > 1:
                    # Look for previous day's data
                    prev_day_data = journey_data[journey_data['day_of_journey'] == day - 1]
                    if not prev_day_data.empty:
                        prev_failures = prev_day_data['treatment_failures'].iloc[0]
                        if pd.notna(prev_failures) and treatment_failures <= prev_failures:
                            is_new_failure = False
                
                if is_new_failure:
                    failure_days.append(day)
        
        # Format failure information
        if failure_days:
            failure_days.sort()  # Sort chronologically
            if len(failure_days) == 1:
                drug_failure_info.append(f"Drug failure: Day {failure_days[0]}")
            else:
                failure_days_str = ", ".join([f"Day {day}" for day in failure_days])
                drug_failure_info.append(f"Drug failures: {failure_days_str}")
        
        return drug_failure_info

    
    def _get_resistance_sources_info(self, journey_data):
        """Extract and format resistance source information for de novo resistance cases."""
        resistance_sources_info = []
        
        # First, identify which drugs were actually used in this journey
        drugs_used = set()
        for _, row in journey_data.iterrows():
            if pd.notna(row['current_drugs']) and row['current_drugs'] != '':
                drug_entries = row['current_drugs'].split(';')
                for entry in drug_entries:
                    if ':' in entry:
                        drug_name, _ = entry.split(':', 1)
                        drugs_used.add(drug_name.strip())
        
        # Get resistance sources only for drugs that were actually used
        all_sources = set()
        
        for _, row in journey_data.iterrows():
            resistance_sources = row.get('resistance_sources', '')
            if pd.notna(resistance_sources) and resistance_sources.strip():
                # Parse the semicolon-separated drug:source pairs
                source_pairs = resistance_sources.split(';')
                for pair in source_pairs:
                    if ':' in pair:
                        drug, source = pair.split(':', 1)
                        drug = drug.strip()
                        # Only include if this drug was actually used in the journey
                        if drug in drugs_used:
                            # Map internal source names to user-friendly names
                            source_display = self._format_resistance_source(source.strip())
                            all_sources.add(f"{drug} ({source_display})")
        
        # Format the resistance sources information
        if all_sources:
            resistance_sources_info.append("⭐ resistance sources:")
            for source in sorted(all_sources):
                resistance_sources_info.append(f"  • {source}")
        
        return resistance_sources_info
    
    def _format_resistance_source(self, source):
        """Convert internal resistance source names to user-friendly display names."""
        source_mapping = {
            'at_infection_community': 'Community infection',
            'at_infection_env': 'Environmental infection', 
            'at_infection_tb': 'TB infection',
            'hgt': 'Horizontal gene transfer',
            'from_microbiome_r': 'From microbiome'
        }
        return source_mapping.get(source, source)

def main(verbose=False, num_timeline_plots=NUM_TIMELINE_PLOTS):
    """Main function to run the analysis."""
    if verbose:
        print("Infection Journey Analysis Tool")
        print("=" * 50)
    
    # Initialize analyzer with verbose setting
    analyzer = InfectionJourneyAnalyzer(verbose=verbose)
    
    # Generate summary report
    analyzer.generate_summary_report()
    
    # Generate detailed text report
    if verbose:
        print(f"\nGenerating detailed text report for all journeys...")
    text_report_file = analyzer.generate_text_report()
    
    # Enhanced journey selection: prioritize de novo resistance cases and stratify across time periods
    
    # First, identify journeys with de novo resistance emergence
    de_novo_journeys = []
    max_de_novo = 5  # Limit de novo journeys to avoid overwhelming the plots
    if 'has_de_novo_resistance' in analyzer.df.columns:
        de_novo_mask = analyzer.df['has_de_novo_resistance'] == True
        all_de_novo = analyzer.df[de_novo_mask]['journey_id'].unique().tolist()
        # Limit to max_de_novo from the start
        de_novo_journeys = all_de_novo[:max_de_novo] if len(all_de_novo) > max_de_novo else all_de_novo
        
    if verbose and len(de_novo_journeys) > 0:
        print(f"\nFound {len(all_de_novo) if 'all_de_novo' in locals() else len(de_novo_journeys)} journeys with de novo resistance emergence!")
        print(f"Including {len(de_novo_journeys)} de novo resistance journeys (max {max_de_novo})")
    
    # Stratified sampling across time periods to reduce early-simulation bias
    # Define time periods: early (before treatment), treatment era, late
    treatment_start_time = 2555  # Treatment starts in 1937 (day 2555)
    
    # Get journey start times (minimum time step for each journey)
    journey_times = analyzer.df.groupby('journey_id')['time_step'].min().reset_index()
    journey_times['period'] = 'early'
    journey_times.loc[journey_times['time_step'] >= treatment_start_time, 'period'] = 'treatment'
    journey_times.loc[journey_times['time_step'] >= treatment_start_time + 2000, 'period'] = 'late'
    
    # Calculate sampling targets per period (bias toward treatment period)
    total_random_slots = max(0, num_timeline_plots - len(de_novo_journeys))
    early_target = max(1, int(total_random_slots * 0.2))  # 20% from early period
    treatment_target = max(1, int(total_random_slots * 0.6))  # 60% from treatment period
    late_target = total_random_slots - early_target - treatment_target  # Remainder from late period
    
    if verbose:
        period_counts = journey_times['period'].value_counts()
        print(f"\nJourney distribution by time period:")
        print(f"Early period (pre-treatment): {period_counts.get('early', 0)} journeys")
        print(f"Treatment period: {period_counts.get('treatment', 0)} journeys") 
        print(f"Late period: {period_counts.get('late', 0)} journeys")
        print(f"\nSampling strategy:")
        print(f"De novo resistance journeys: {len(de_novo_journeys)} (always included)")
        print(f"Random from early period: {early_target}")
        print(f"Random from treatment period: {treatment_target}")
        print(f"Random from late period: {late_target}")
    
    # Sample from each period, redistributing unfilled targets
    selected_journeys = de_novo_journeys.copy()  # Always include de novo resistance cases
    
    period_targets = [('early', early_target), ('treatment', treatment_target), ('late', late_target)]
    
    # First pass: sample what we can from each period
    unfilled_slots = 0
    for period, target in period_targets:
        period_journeys = journey_times[journey_times['period'] == period]['journey_id'].values
        # Exclude already selected de novo journeys
        period_journeys = [j for j in period_journeys if j not in selected_journeys]
        
        if len(period_journeys) > 0 and target > 0:
            sample_size = min(target, len(period_journeys))
            sampled = np.random.choice(period_journeys, size=sample_size, replace=False)
            selected_journeys.extend(sampled.tolist())
            # Track how many slots were left unfilled from this period
            unfilled_slots += (target - sample_size)
        else:
            # Track completely unfilled slots
            unfilled_slots += target
    
    # Second pass: if we have unfilled slots, redistribute to available periods
    if unfilled_slots > 0:
        all_available = [j for j in journey_times['journey_id'].values if j not in selected_journeys]
        if len(all_available) > 0:
            additional_sample_size = min(unfilled_slots, len(all_available))
            additional_sampled = np.random.choice(all_available, size=additional_sample_size, replace=False)
            selected_journeys.extend(additional_sampled.tolist())
    
    # Trim to requested number if we somehow exceeded it
    journeys_to_plot = selected_journeys[:num_timeline_plots]
    
    if verbose:
        print(f"\nTotal journeys selected: {len(journeys_to_plot)}")
        print(f"Generating individual journey timeline plots...")
        if len(de_novo_journeys) > 0:
            print(f"⭐ {len([j for j in journeys_to_plot if j in de_novo_journeys])} de novo resistance journeys included (max {max_de_novo})")
    
    for i, journey_id in enumerate(journeys_to_plot, 1):
        is_de_novo = journey_id in de_novo_journeys
        analyzer.view_individual_journey(journey_id=journey_id, sequential_number=i, highlight_de_novo=is_de_novo)
    
    if verbose:
        print(f"\nAvailable journey IDs (showing first 20): {list(analyzer.df['journey_id'].unique()[:20])}")
    
    # Create population-level visualizations
    state_counts = analyzer.plot_infection_states_over_time(max_days=30)
    
    # Calculate mortality analysis
    mortality_analysis = analyzer.calculate_30_day_mortality()
    
    if verbose:
        print(f"\nAnalysis complete! Files generated:")
        print(f"  📊 Figures: {analyzer.output_dir}/*.png")
        print(f"  📄 Text report: {text_report_file}")
        print(f"\nUse the following methods for further exploration:")
        print(f"  analyzer.view_individual_journey(journey_id=X)  # View specific journey")
        print(f"  analyzer.plot_infection_states_over_time()      # Population infection states")
        print(f"  analyzer.calculate_30_day_mortality()           # Mortality analysis")
        print(f"  analyzer.generate_text_report()                 # Generate detailed text report")
    
    return analyzer

if __name__ == "__main__":
    # Configuration is set at the top of this file
    # Modify NUM_TIMELINE_PLOTS and VERBOSE_OUTPUT variables to change behavior
    analyzer = main(verbose=VERBOSE_OUTPUT, num_timeline_plots=NUM_TIMELINE_PLOTS)