"""
Infection Journ# import seaborn as sns  # Commented out to avoid import issuesy Analysis Script

This script analyzes the infection_journeys.csv file generated by the AMR simulation
to provide insights into individual patient journeys and population-level outcomes.

Features:
1. View individual patient journeys with timeline visualization
2. Create stacked graphs of infection outcomes by day
3. Calculate 30-day mortality probability from infection onset
4. Summary statistics and outcome analysis

Author: Generated for AMR simulation analysis
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend for saving files only
import matplotlib.pyplot as plt
# import se                syndrome_name = self.syndrome_names.get(journey['syndrome'], f\"Syndrome {journey['syndrome']}\")\n                f.write(f\"Syndrome: {syndrome_name}\\n\")               syndrome_name = self.syndrome_names.get(journey['syndrome'], f\"Syndrome {journey['syndrome']}\")\n                f.write(f\"Syndrome: {syndrome_name}\\n\")born as sns  # Commented out to avoid import issues
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# =============================================================================
# CONFIGURATION SETTINGS - Modify these values as needed
# =============================================================================

# Number of individual journey timeline plots to generate
# Recommended range: 1-50 (higher numbers create more files)
# Files will be named: journey_01_timeline.png, journey_02_timeline.png, etc.
NUM_TIMELINE_PLOTS = 30

# Number of journeys to include in detailed text report
# Recommended range: 1-20 (higher numbers create much larger text files)
# Set to 0 to skip detailed report generation entirely
NUM_DETAILED_JOURNEYS = 30

# Enable verbose output during analysis
# True: Shows detailed progress messages and analysis results
# False: Silent operation (still generates all files)
VERBOSE_OUTPUT = False

# =============================================================================

class InfectionJourneyAnalyzer:
    def __init__(self, csv_file="infection_journeys.csv", output_dir="infection_journey_analysis_outputs", verbose=True):
        """Initialize the analyzer with the journey data."""
        self.verbose = verbose
        self.plot_counter = 0  # Counter for sequential plot numbering
        if self.verbose:
            print(f"Loading infection journey data from {csv_file}...")
        self.df = pd.read_csv(csv_file)
        self.output_dir = output_dir
        
        # Create output directory if it doesn't exist
        import os
        os.makedirs(output_dir, exist_ok=True)
        
        self.process_data()
        if self.verbose:
            print(f"Loaded {len(self.df)} journey snapshots for {self.df['journey_id'].nunique()} unique journeys")
            print(f"Figures will be saved to: {output_dir}")
        
    def process_data(self):
        """Process and clean the loaded data."""
        # Convert boolean columns
        bool_cols = ['sepsis', 'hospital_acquired', 'infection_identified', 'resistance_testing_done']
        for col in bool_cols:
            self.df[col] = self.df[col].astype(bool)
            
        # Create treatment status
        self.df['is_treated'] = self.df['current_drugs'].notna() & (self.df['current_drugs'] != "")
        
        # Create infection state categories
        self.df['infection_state'] = 'Unknown'
        self.df.loc[self.df['sepsis'] == True, 'infection_state'] = 'Sepsis'
        self.df.loc[(self.df['sepsis'] == False) & (self.df['is_treated'] == True), 'infection_state'] = 'Treated'
        self.df.loc[(self.df['sepsis'] == False) & (self.df['is_treated'] == False), 'infection_state'] = 'Not Treated'
        
        # Syndrome mapping (syndromes 1-10)
        self.syndrome_names = {
            1: "Bloodstream infection",
            2: "Pneumonia", 
            3: "Urinary tract infection",
            4: "Skin/soft tissue infection",
            5: "Intra-abdominal infection",
            6: "Central nervous system infection",
            7: "Bone/joint infection",
            8: "Endocarditis", 
            9: "Surgical site infection",
            10: "Other/unspecified infection"
        }
        
        # Process resolution types
        self.df['resolution_type'] = self.df['resolution_type'].fillna('Ongoing')
        
        # Create journey summaries
        self.journey_summary = self._create_journey_summary()
        
    def parse_drug_data(self, drug_string):
        """Parse drug data string into list of (drug_name, level) tuples."""
        if pd.isna(drug_string) or drug_string == "":
            return []
        
        drugs = []
        for item in drug_string.split(";"):
            if ":" in item:
                drug_name, level = item.split(":")
                drugs.append((drug_name.strip(), float(level)))
        return drugs
    
    def _create_journey_summary(self):
        """Create summary statistics for each journey."""
        summary_stats = []
        
        for journey_id in self.df['journey_id'].unique():
            journey_data = self.df[self.df['journey_id'] == journey_id].copy()
            journey_data = journey_data.sort_values('day_of_journey')
            
            summary = {
                'journey_id': journey_id,
                'individual_id': journey_data['individual_id'].iloc[0],
                'age_at_onset': journey_data['age_at_onset'].iloc[0],
                'sex': journey_data['sex'].iloc[0],
                'region': journey_data['region_living'].iloc[0],
                'primary_bacteria': journey_data['primary_bacteria'].iloc[0],
                'syndrome': journey_data['syndrome'].iloc[0],
                'immunodeficiency': journey_data['immunodeficiency'].iloc[0],
                'hospital_acquired': journey_data['hospital_acquired'].iloc[0],
                'duration_days': journey_data['day_of_journey'].max(),
                'max_bacteria_level': journey_data['primary_bacteria_level'].max(),
                'developed_sepsis': journey_data['sepsis'].any(),
                'was_treated': journey_data['is_treated'].any(),
                'treatment_failures': journey_data['treatment_failures'].max(),
                'resolution_type': self._determine_actual_resolution(journey_data),
                'died': self._determine_actual_resolution(journey_data) == 'Death',
                'died_within_30_days': (self._determine_actual_resolution(journey_data) == 'Death') and (journey_data['day_of_journey'].max() <= 30),
                'drug_selection_occurred': journey_data['drug_selection_bacteria'].notna().any(),
                'selected_drug': journey_data['selected_drug'].dropna().iloc[0] if journey_data['selected_drug'].notna().any() else None
            }
            summary_stats.append(summary)
            
        return pd.DataFrame(summary_stats)
    
    def view_individual_journey(self, journey_id=None, individual_id=None, sequential_number=None):
        """View detailed timeline for a specific journey."""
        if journey_id is not None:
            journey_data = self.df[self.df['journey_id'] == journey_id].copy()
        elif individual_id is not None:
            journey_data = self.df[self.df['individual_id'] == individual_id].copy()
        else:
            # Show first available journey
            journey_data = self.df[self.df['journey_id'] == self.df['journey_id'].iloc[0]].copy()
            
        if journey_data.empty:
            if self.verbose:
                print("No journey found with the specified criteria.")
            return
            
        journey_data = journey_data.sort_values('day_of_journey')
        journey_id = journey_data['journey_id'].iloc[0]
        individual_id = journey_data['individual_id'].iloc[0]
        
        if self.verbose:
            print(f"\n{'='*80}")
            print(f"INFECTION JOURNEY ANALYSIS - Journey ID: {journey_id}, Individual ID: {individual_id}")
            print(f"{'='*80}")
            
            # Patient demographics
            print(f"Patient Demographics:")
            print(f"  Age at onset: {journey_data['age_at_onset'].iloc[0]} days ({journey_data['age_at_onset'].iloc[0]/365.25:.1f} years)")
            print(f"  Sex: {journey_data['sex'].iloc[0]}")
            print(f"  Region: {journey_data['region_living'].iloc[0]}")
            print(f"  Immunodeficiency: {journey_data['immunodeficiency'].iloc[0]}")
            
            # Infection characteristics
            print(f"\nInfection Characteristics:")
            print(f"  Primary bacteria: {journey_data['primary_bacteria'].iloc[0]}")
            print(f"  Syndrome: {journey_data['syndrome'].iloc[0]}")
            print(f"  Hospital acquired: {journey_data['hospital_acquired'].iloc[0]}")
            print(f"  Journey duration: {journey_data['day_of_journey'].max()} days")
            print(f"  Final resolution: {journey_data['resolution_type'].iloc[-1]}")
        
        # Create timeline visualization
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 10))
        fig.suptitle(f'Journey Timeline - ID: {journey_id}', fontsize=14, fontweight='bold')
        
        days = journey_data['day_of_journey']
        
        # Bacteria level over time with sepsis-aware coloring
        sepsis_status = journey_data['sepsis'].values
        bacteria_levels = journey_data['primary_bacteria_level'].values
        
        # Plot segments with different colors based on sepsis status
        for i in range(len(days) - 1):
            color = 'red' if sepsis_status[i] else 'blue'
            ax1.plot(days.iloc[i:i+2], bacteria_levels[i:i+2], color=color, linewidth=4)
            
        # Add markers
        sepsis_mask = sepsis_status
        no_sepsis_mask = ~sepsis_status
        if no_sepsis_mask.any():
            ax1.scatter(days[no_sepsis_mask], bacteria_levels[no_sepsis_mask], 
                       color='blue', marker='o', s=20, label='No sepsis', zorder=5)
        if sepsis_mask.any():
            ax1.scatter(days[sepsis_mask], bacteria_levels[sepsis_mask], 
                       color='red', marker='o', s=20, label='Sepsis', zorder=5)
        
        ax1.set_title('Primary Bacteria Level')
        ax1.set_xlabel('Day of Journey', fontsize=20)
        ax1.set_ylabel('Bacteria Level', fontsize=20)
        ax1.set_xticks(range(int(days.min()), int(days.max()) + 1))
        ax1.set_ylim(bottom=0)  # Ensure y-axis starts at 0
        ax1.grid(True, alpha=0.3)
        if sepsis_mask.any():
            ax1.legend(fontsize=8)
        
        # Immunity and toxicity levels
        ax2.plot(days, journey_data['immunity_level'], 'g-', marker='s', label='Immunity', linewidth=4, markersize=4)
        ax2.plot(days, journey_data['toxicity_level'], 'r-', marker='^', label='Toxicity', linewidth=4, markersize=4)
        ax2.set_title('Immunity & Toxicity Levels')
        ax2.set_xlabel('Day of Journey', fontsize=20)
        ax2.set_ylabel('Level', fontsize=20)
        ax2.set_xticks(range(int(days.min()), int(days.max()) + 1))
        ax2.set_ylim(bottom=0)  # Ensure y-axis starts at 0
        ax2.legend()
        ax2.grid(True, alpha=0.3)
        
        # Drug levels and resistance (activity_r)
        # Parse drug data to get levels and activity_r values
        drug_data = self._parse_drug_and_resistance_data(journey_data)
        
        if drug_data['has_drugs']:
            # Plot drug levels from when treatment starts
            for drug_name, drug_levels in drug_data['drug_levels'].items():
                mask = ~pd.isna(drug_levels)
                if mask.any():
                    ax3.plot(days[mask], drug_levels[mask], color='#FF8C00', marker='o', 
                            label=f'{drug_name} Level', linewidth=4, markersize=3)
            
            # Plot activity_r on secondary y-axis
            ax3_twin = ax3.twinx()
            for drug_name, activity_r in drug_data['activity_r'].items():
                mask = ~pd.isna(activity_r) & (activity_r > 0)
                if mask.any():
                    ax3_twin.plot(days[mask], activity_r[mask], color='#9370DB', linestyle='--', marker='s', 
                                 label=f'{drug_name} Activity R', linewidth=4, markersize=3)
            
            ax3.set_xlabel('Day of Journey', fontsize=20)
            ax3.set_ylabel('Drug Level', color='#FF8C00', fontsize=20)
            ax3_twin.set_ylabel('Activity R', color='#9370DB', fontsize=20)
            ax3.set_title('Drug Levels & Resistance (Activity R)')
            ax3.set_xticks(range(int(days.min()), int(days.max()) + 1))
            ax3.set_ylim(bottom=0)  # Ensure drug level y-axis starts at 0
            ax3_twin.set_ylim(bottom=0)  # Ensure activity R y-axis starts at 0
            ax3.grid(True, alpha=0.3)
            
            # Combine legends
            lines1, labels1 = ax3.get_legend_handles_labels()
            lines2, labels2 = ax3_twin.get_legend_handles_labels()
            if lines1 or lines2:
                ax3.legend(lines1 + lines2, labels1 + labels2, loc='upper left', fontsize=8)
        else:
            ax3.text(0.5, 0.5, 'No drug treatment', transform=ax3.transAxes, 
                    ha='center', va='center', fontsize=12)
            ax3.set_title('Drug Levels & Resistance (Activity R)')
            ax3.set_xlabel('Day of Journey', fontsize=20)
            ax3.set_xticks(range(int(days.min()), int(days.max()) + 1))
            ax3.set_ylim(bottom=0)  # Ensure y-axis starts at 0 even with no data
        
        # Clinical summary text (replacing hospital status plot)
        ax4.axis('off')  # Turn off axis for text display
        
        # Prepare clinical summary information
        # Calculate calendar year
        first_time_step = journey_data['time_step'].iloc[0]
        calendar_year = int(first_time_step / 365) + 1930
        
        # Find testing days
        bacteria_id_day = None
        if journey_data['infection_identified'].any():
            bacteria_id_day = journey_data[journey_data['infection_identified']]['day_of_journey'].min()
        
        resistance_test_day = None
        if journey_data['resistance_testing_done'].any():
            resistance_test_day = journey_data[journey_data['resistance_testing_done']]['day_of_journey'].min()
        
        sepsis_day = None
        if journey_data['sepsis'].any():
            sepsis_day = journey_data[journey_data['sepsis']]['day_of_journey'].min()
        
        death_day = None
        death_cause = journey_data['resolution_type'].iloc[-1]
        is_death = False
        
        # Check for death resolution types
        if pd.notna(death_cause) and ('Death' in str(death_cause)):
            is_death = True
            death_day = journey_data['day_of_journey'].max()
        
        # Check if journey is ongoing (NaN resolution)
        is_ongoing = pd.isna(death_cause) or death_cause == ''
        
        # Format clinical information
        if is_ongoing:
            outcome_text = f"Ongoing ({journey_data['day_of_journey'].max()} days)"
        elif is_death:
            outcome_text = f"Died Day {death_day} ({death_cause})"
        else:
            outcome_text = f"Recovered ({death_cause})"
        
        # Get syndrome name
        syndrome_num = journey_data['syndrome'].iloc[0]
        syndrome_name = self.syndrome_names.get(syndrome_num, f"Syndrome {syndrome_num}")
        
        clinical_info = [
            f"Year: {calendar_year}",
            f"Bacteria: {journey_data['primary_bacteria'].iloc[0]}",
            f"Region: {journey_data['region_living'].iloc[0]}",
            f"Age: {journey_data['age_at_onset'].iloc[0]/365.25:.1f} years",
            f"Syndrome: {syndrome_name}",
            f"Sepsis: {'Day ' + str(sepsis_day) if sepsis_day else 'None'}",
            f"Bacteria identified: {'Day ' + str(bacteria_id_day) if bacteria_id_day else 'None'}",
            f"Resistance test: {'Day ' + str(resistance_test_day) if resistance_test_day else 'None'}",
            f"Outcome: {outcome_text}",
            f"Duration: {journey_data['day_of_journey'].max()} days",
            f"Hospital acquired: {'Yes' if journey_data['hospital_acquired'].iloc[0] else 'No'}"
        ]
        
        # Display clinical information as text with reduced vertical spacing
        ax4.text(0.05, 0.95, "Clinical Summary", transform=ax4.transAxes, 
                fontsize=12, fontweight='bold', va='top')
        
        for i, info in enumerate(clinical_info):
            ax4.text(0.05, 0.87 - i*0.07, info, transform=ax4.transAxes, 
                    fontsize=10, va='top', family='monospace')
        
        plt.tight_layout()
        
        # Save the figure with sequential numbering
        if sequential_number is not None:
            filename = f"journey_{sequential_number:02d}_timeline.png"
        else:
            # Auto-increment counter if no specific number provided
            self.plot_counter += 1
            filename = f"journey_{self.plot_counter:02d}_timeline.png"
        filepath = f"{self.output_dir}/{filename}"
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        if self.verbose:
            print(f"Saved individual journey plot: {filepath}")
        
        plt.close()  # Close figure to free memory
        
        # Print detailed day-by-day progression
        if self.verbose:
            print(f"\nDay-by-Day Progression:")
            print(f"{'Day':>3} {'Bacteria':>8} {'Immunity':>8} {'Toxicity':>8} {'Treated':>7} {'Sepsis':>6} {'Hospital':>10}")
            print("-" * 65)
            
            for _, row in journey_data.iterrows():
                treated = 'Yes' if row['is_treated'] else 'No'
                sepsis = 'Yes' if row['sepsis'] else 'No'
                print(f"{row['day_of_journey']:>3} {row['primary_bacteria_level']:>8.3f} {row['immunity_level']:>8.3f} "
                      f"{row['toxicity_level']:>8.3f} {treated:>7} {sepsis:>6} {row['hospital_status']:>10}")
    
    def plot_infection_states_over_time(self, max_days=30):
        """Create stacked bar chart of infection states by day."""
        if self.verbose:
            print(f"\nCreating infection states visualization (first {max_days} days)...")
        
        # Filter to first N days for readability
        daily_data = self.df[self.df['day_of_journey'] <= max_days].copy()
        
        # Count states by day
        state_counts = daily_data.groupby(['day_of_journey', 'infection_state']).size().unstack(fill_value=0)
        
        # Create stacked bar chart
        fig, ax = plt.subplots(figsize=(14, 8))
        
        colors = {'Not Treated': '#FF6B6B', 'Treated': '#4ECDC4', 'Sepsis': '#45B7D1', 'Unknown': '#96CEB4'}
        state_counts.plot(kind='bar', stacked=True, ax=ax, color=[colors.get(col, '#95A5A6') for col in state_counts.columns])
        
        ax.set_title(f'Infection States Over Time (First {max_days} Days)', fontsize=14, fontweight='bold')
        ax.set_xlabel('Day of Journey')
        ax.set_ylabel('Number of Individuals')
        ax.legend(title='Infection State', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.grid(True, alpha=0.3, axis='y')
        
        # Set x-axis to show whole days
        day_range = range(1, max_days + 1)
        ax.set_xticks(range(len(state_counts.index)))
        ax.set_xticklabels([str(day) for day in state_counts.index])
        plt.xticks(rotation=45)
        plt.tight_layout()
        
        # Save the figure
        filename = f"infection_states_stacked_first_{max_days}_days.png"
        filepath = f"{self.output_dir}/{filename}"
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        if self.verbose:
            print(f"Saved infection states plot: {filepath}")
        
        plt.close()  # Close figure to free memory
        
        return state_counts
    
    def calculate_30_day_mortality(self):
        """Calculate and visualize 30-day mortality probability."""
        if self.verbose:
            print("\nCalculating 30-day mortality analysis...")
        
        # Filter journeys that either died within 30 days or survived at least 30 days
        mortality_analysis = []
        
        for journey_id in self.journey_summary['journey_id'].unique():
            journey_info = self.journey_summary[self.journey_summary['journey_id'] == journey_id].iloc[0]
            
            # Include if journey lasted at least 30 days OR ended in death
            if journey_info['duration_days'] >= 30 or journey_info['died']:
                mortality_analysis.append({
                    'journey_id': journey_id,
                    'died_within_30_days': journey_info['died_within_30_days'],
                    'duration_days': min(journey_info['duration_days'], 30),
                    'age_at_onset': journey_info['age_at_onset'],
                    'sex': journey_info['sex'],
                    'primary_bacteria': journey_info['primary_bacteria'],
                    'developed_sepsis': journey_info['developed_sepsis'],
                    'was_treated': journey_info['was_treated']
                })
        
        mortality_df = pd.DataFrame(mortality_analysis)
        
        if len(mortality_df) == 0:
            if self.verbose:
                print("No journeys available for 30-day mortality analysis.")
            return None
        
        # Calculate overall 30-day mortality rate
        overall_mortality = mortality_df['died_within_30_days'].mean()
        if self.verbose:
            print(f"Overall 30-day mortality rate: {overall_mortality:.1%} ({mortality_df['died_within_30_days'].sum()}/{len(mortality_df)} cases)")
        
        # Create mortality analysis plots
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 10))
        fig.suptitle('30-Day Mortality Analysis', fontsize=14, fontweight='bold')
        
        # Mortality by bacteria type
        bacteria_mortality = mortality_df.groupby('primary_bacteria')['died_within_30_days'].agg(['count', 'sum', 'mean']).reset_index()
        bacteria_mortality = bacteria_mortality[bacteria_mortality['count'] >= 5]  # At least 5 cases
        bacteria_mortality = bacteria_mortality.sort_values('mean', ascending=True)
        
        if len(bacteria_mortality) > 0:
            ax1.barh(range(len(bacteria_mortality)), bacteria_mortality['mean'], color='crimson', alpha=0.7)
            ax1.set_yticks(range(len(bacteria_mortality)))
            ax1.set_yticklabels([name.replace('_', ' ').title() for name in bacteria_mortality['primary_bacteria']])
            ax1.set_xlabel('30-Day Mortality Rate')
            ax1.set_title('Mortality by Bacteria Type')
            ax1.grid(True, alpha=0.3, axis='x')
        
        # Mortality by sepsis development
        sepsis_mortality = mortality_df.groupby('developed_sepsis')['died_within_30_days'].mean()
        ax2.bar(['No Sepsis', 'Developed Sepsis'], sepsis_mortality.values, color=['lightblue', 'darkred'], alpha=0.7)
        ax2.set_ylabel('30-Day Mortality Rate')
        ax2.set_title('Mortality by Sepsis Development')
        ax2.grid(True, alpha=0.3, axis='y')
        
        # Mortality by treatment status
        treatment_mortality = mortality_df.groupby('was_treated')['died_within_30_days'].mean()
        ax3.bar(['Not Treated', 'Treated'], treatment_mortality.values, color=['orange', 'green'], alpha=0.7)
        ax3.set_ylabel('30-Day Mortality Rate')
        ax3.set_title('Mortality by Treatment Status')
        ax3.grid(True, alpha=0.3, axis='y')
        
        # Age distribution of deaths vs survivors
        died_ages = mortality_df[mortality_df['died_within_30_days']]['age_at_onset'] / 365.25
        survived_ages = mortality_df[~mortality_df['died_within_30_days']]['age_at_onset'] / 365.25
        
        ax4.hist([died_ages, survived_ages], bins=20, alpha=0.7, label=['Died', 'Survived'], color=['red', 'blue'])
        ax4.set_xlabel('Age at Onset (years)')
        ax4.set_ylabel('Frequency')
        ax4.set_title('Age Distribution: Deaths vs Survivors')
        ax4.legend()
        ax4.grid(True, alpha=0.3, axis='y')
        
        plt.tight_layout()
        
        # Save the figure
        filename = "30_day_mortality_analysis.png"
        filepath = f"{self.output_dir}/{filename}"
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        if self.verbose:
            print(f"Saved mortality analysis plot: {filepath}")
        
        plt.close()  # Close figure to free memory
        
        return mortality_df
    
    def detect_death_day(self, journey_data):
        """Detect the day when death likely occurred based on static values"""
        if len(journey_data) < 10:  # Need sufficient data points
            return None
            
        # Look for patterns indicating death (static values for extended periods)
        for start_idx in range(5, len(journey_data) - 5):  # Start checking after day 5
            current_row = journey_data.iloc[start_idx]
            
            # Check if the next 5+ days have identical values (indicating death/simulation stop)
            static_count = 0
            for check_idx in range(start_idx, min(start_idx + 10, len(journey_data))):
                check_row = journey_data.iloc[check_idx]
                
                # Check if key values are identical (indicating simulation stopped)
                if (abs(check_row['primary_bacteria_level'] - current_row['primary_bacteria_level']) < 0.001 and
                    abs(check_row['immunity_level'] - current_row['immunity_level']) < 0.001 and
                    abs(check_row['toxicity_level'] - current_row['toxicity_level']) < 0.001 and
                    check_row['sepsis'] == current_row['sepsis'] and
                    check_row['is_treated'] == current_row['is_treated']):
                    static_count += 1
                else:
                    break
            
            # If we found 5+ consecutive identical days, death likely occurred
            if static_count >= 5:
                return current_row['day_of_journey']
        
        return None
    
    def determine_death_cause(self, death_row):
        """Determine the likely cause of death based on final state"""
        causes = []
        
        # High toxicity death
        if death_row['toxicity_level'] > 3.5:
            causes.append("Toxicity")
        
        # Sepsis death
        if death_row['sepsis']:
            causes.append("Sepsis")
        
        # Severe infection death
        if death_row['primary_bacteria_level'] > 3.0:
            causes.append("Severe infection")
        
        # Default if no clear cause identified
        if not causes:
            causes.append("Multi-organ failure")
        
        return " + ".join(causes)
    
    def _parse_drug_and_resistance_data(self, journey_data):
        """Parse drug levels and resistance data from journey data"""
        drug_data = {
            'has_drugs': False,
            'drug_levels': {},
            'activity_r': {}
        }
        
        # Check if there are any drugs in this journey
        has_treatment = journey_data['current_drugs'].notna() & (journey_data['current_drugs'] != "")
        if not has_treatment.any():
            return drug_data
        
        drug_data['has_drugs'] = True
        
        # Parse current_drugs field to extract drug names and levels
        for _, row in journey_data.iterrows():
            if pd.isna(row['current_drugs']) or row['current_drugs'] == "":
                continue
                
            # Parse drug string format: "drug1:level1;drug2:level2"
            drugs_str = row['current_drugs']
            if drugs_str and isinstance(drugs_str, str):
                for drug_entry in drugs_str.split(';'):
                    if ':' in drug_entry:
                        drug_name, level_str = drug_entry.split(':', 1)
                        drug_name = drug_name.strip()
                        try:
                            level = float(level_str.strip())
                            if drug_name not in drug_data['drug_levels']:
                                drug_data['drug_levels'][drug_name] = pd.Series(index=journey_data.index, dtype=float)
                            drug_data['drug_levels'][drug_name].loc[row.name] = level
                        except ValueError:
                            continue
        
        # Parse resistance_activity_r field  
        for _, row in journey_data.iterrows():
            if pd.isna(row['resistance_activity_r']) or row['resistance_activity_r'] == "":
                continue
                
            # Parse resistance string format: "drug1:value1;drug2:value2"
            resistance_str = row['resistance_activity_r']
            if resistance_str and isinstance(resistance_str, str):
                for resistance_entry in resistance_str.split(';'):
                    if ':' in resistance_entry:
                        drug_name, value_str = resistance_entry.split(':', 1)
                        drug_name = drug_name.strip()
                        try:
                            value = float(value_str.strip())
                            if drug_name not in drug_data['activity_r']:
                                drug_data['activity_r'][drug_name] = pd.Series(index=journey_data.index, dtype=float)
                            drug_data['activity_r'][drug_name].loc[row.name] = value
                        except ValueError:
                            continue
        
        return drug_data
    
    def _determine_actual_resolution(self, journey_data):
        """Determine the actual resolution based on the data"""
        final_resolution = journey_data['resolution_type'].iloc[-1]
        
        # If resolution is NaN or empty, it's an ongoing journey
        if pd.isna(final_resolution) or final_resolution == '':
            return 'Ongoing'
        
        # Otherwise use the resolution from the data
        return final_resolution
    
    def generate_text_report(self):
        """Generate comprehensive text report file with detailed journey listings."""
        filename = f"{self.output_dir}/infection_journeys_detailed_report.txt"
        
        with open(filename, 'w') as f:
            # Write header
            f.write("="*80 + "\n")
            f.write("DETAILED INFECTION JOURNEY ANALYSIS REPORT\n")
            f.write("="*80 + "\n")
            f.write(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Total journeys: {len(self.journey_summary)}\n")
            f.write(f"Total snapshots: {len(self.df):,}\n\n")
            
            # Summary statistics
            f.write("SUMMARY STATISTICS\n")
            f.write("-" * 40 + "\n")
            f.write(f"Average journey length: {self.df.groupby('journey_id')['day_of_journey'].max().mean():.1f} days\n")
            f.write(f"Journeys with sepsis: {self.journey_summary['developed_sepsis'].sum()} ({self.journey_summary['developed_sepsis'].mean()*100:.1f}%)\n")
            f.write(f"Journeys with treatment: {self.journey_summary['was_treated'].sum()} ({self.journey_summary['was_treated'].mean()*100:.1f}%)\n")
            f.write(f"Journeys with drug selection events: {self.journey_summary['drug_selection_occurred'].sum()}\n")
            f.write(f"Hospital acquired infections: {self.journey_summary['hospital_acquired'].sum()} ({self.journey_summary['hospital_acquired'].mean()*100:.1f}%)\n\n")
            
            # Resolution type breakdown
            f.write("JOURNEY OUTCOMES\n")
            f.write("-" * 40 + "\n")
            resolution_counts = self.journey_summary['resolution_type'].value_counts()
            for resolution, count in resolution_counts.items():
                percentage = count / len(self.journey_summary) * 100
                f.write(f"  {resolution}: {count:,} ({percentage:.1f}%)\n")
            f.write("\n")
            
            # Bacteria breakdown
            f.write("BACTERIA DISTRIBUTION\n")
            f.write("-" * 40 + "\n")
            bacteria_counts = self.journey_summary['primary_bacteria'].value_counts().head(15)
            for bacteria, count in bacteria_counts.items():
                percentage = count / len(self.journey_summary) * 100
                f.write(f"  {bacteria.replace('_', ' ').title()}: {count:,} ({percentage:.1f}%)\n")
            f.write("\n")
            
            # Detailed individual journey listings
            f.write("="*80 + "\n")
            f.write("DETAILED INDIVIDUAL JOURNEY LISTINGS\n")
            f.write("="*80 + "\n\n")
            
            # Sort journeys by ID for consistent ordering
            journeys_to_process = self.journey_summary.sort_values('journey_id').head(NUM_DETAILED_JOURNEYS)
            f.write(f"Showing detailed analysis for first {NUM_DETAILED_JOURNEYS} journeys (out of {len(self.journey_summary)} total)\n\n")
            
            for idx, (_, journey) in enumerate(journeys_to_process.iterrows(), 1):
                journey_id = journey['journey_id']
                journey_data = self.df[self.df['journey_id'] == journey_id].copy()
                journey_data = journey_data.sort_values('day_of_journey')
                
                f.write(f"JOURNEY #{idx} (ID: {journey_id})\n")
                f.write("-" * 60 + "\n")
                
                # Calculate calendar year from time_step
                first_time_step = journey_data['time_step'].iloc[0]
                calendar_year = int(first_time_step / 365) + 1930
                
                # Patient demographics
                f.write(f"Patient ID: {journey['individual_id']}\n")
                f.write(f"Calendar year: {calendar_year}\n")
                f.write(f"Age at onset: {journey['age_at_onset']} days ({journey['age_at_onset']/365.25:.1f} years)\n")
                f.write(f"Sex: {journey['sex']}\n")
                f.write(f"Region: {journey['region']}\n")
                f.write(f"Immunodeficiency: {journey['immunodeficiency']}\n\n")
                
                # Infection characteristics
                f.write(f"Primary bacteria: {journey['primary_bacteria'].replace('_', ' ').title()}\n")
                syndrome_name = self.syndrome_names.get(journey['syndrome'], f"Syndrome {journey['syndrome']}")
                f.write(f"Syndrome: {syndrome_name}\n")
                f.write(f"Hospital acquired: {journey['hospital_acquired']}\n")
                f.write(f"Journey duration: {journey['duration_days']} days\n")
                f.write(f"Maximum bacteria level: {journey['max_bacteria_level']:.3f}\n")
                f.write(f"Developed sepsis: {journey['developed_sepsis']}\n")
                f.write(f"Received treatment: {journey['was_treated']}\n")
                f.write(f"Treatment failures: {journey['treatment_failures']}\n")
                
                # Add testing information
                bacteria_id_day = None
                if journey_data['infection_identified'].any():
                    bacteria_id_day = journey_data[journey_data['infection_identified']]['day_of_journey'].min()
                
                resistance_test_day = None
                if journey_data['resistance_testing_done'].any():
                    resistance_test_day = journey_data[journey_data['resistance_testing_done']]['day_of_journey'].min()
                
                f.write(f"Bacteria identified: {'Day ' + str(bacteria_id_day) if bacteria_id_day else 'Not identified'}\n")
                f.write(f"Resistance testing: {'Day ' + str(resistance_test_day) if resistance_test_day else 'Not performed'}\n")
                if journey['drug_selection_occurred']:
                    f.write(f"Selected drug: {journey['selected_drug']}\n")
                else:
                    f.write(f"No drug selection recorded\n")
                # Show corrected resolution (detect death if present)
                actual_resolution = self._determine_actual_resolution(journey_data)
                if actual_resolution != journey['resolution_type']:
                    f.write(f"Final resolution: {actual_resolution} (originally recorded as: {journey['resolution_type']})\n\n")
                else:
                    f.write(f"Final resolution: {actual_resolution}\n\n")
                
                # Drug selection information if available (only show meaningful selections)
                drug_selection_data = journey_data[journey_data['drug_selection_bacteria'].notna()]
                if not drug_selection_data.empty:
                    f.write("Drug Selection Information:\n")
                    displayed_selections = set()
                    for _, selection_row in drug_selection_data.iterrows():
                        # Parse drug scores to see if this is a meaningful selection
                        scores = self.parse_drug_data(selection_row['drug_selection_scores'])
                        has_selected_drug = pd.notna(selection_row['selected_drug']) and selection_row['selected_drug'] != ""
                        
                        # Only show if we have scores or a selected drug, and haven't shown this selection already
                        selection_key = (selection_row['day_of_journey'], selection_row['drug_selection_bacteria'])
                        if (scores or has_selected_drug) and selection_key not in displayed_selections:
                            displayed_selections.add(selection_key)
                            f.write(f"Day {selection_row['day_of_journey']}: Drug selection for {selection_row['drug_selection_bacteria']}\n")
                            
                            if scores:
                                f.write("  Drug scores at selection time:\n")
                                # Sort by score (highest first)
                                scores.sort(key=lambda x: x[1], reverse=True)
                                for drug_name, score in scores:
                                    f.write(f"    {drug_name}: {score:.4f}\n")
                            
                            if has_selected_drug:
                                f.write(f"  Selected drug: {selection_row['selected_drug']}\n")
                            f.write("\n")
                
                # Day-by-day progression (show ALL days until death)
                f.write("Day-by-day progression:\n")
                f.write("day | bacteria | immunity | toxicity | drugs (level)        | majority_r | activity_r | sepsis | hospital    | death                 | notes\n")
                f.write("-" * 165 + "\n")
                
                # Identify key milestone days for annotations
                treatment_starts = journey_data[journey_data['is_treated'] & ~journey_data['is_treated'].shift(1, fill_value=False)]
                sepsis_starts = journey_data[journey_data['sepsis'] & ~journey_data['sepsis'].shift(1, fill_value=False)]
                hospital_changes = journey_data[journey_data['hospital_status'] != journey_data['hospital_status'].shift(1, fill_value='')]
                
                treatment_start_days = set(treatment_starts['day_of_journey'].tolist())
                sepsis_start_days = set(sepsis_starts['day_of_journey'].tolist())
                hospital_change_days = set(hospital_changes['day_of_journey'].tolist())
                
                # Detect death by looking for static values (indicating simulation stopped processing)
                death_day = self.detect_death_day(journey_data)
                
                # Show days until death (or all days if no death detected)
                last_day_to_show = death_day if death_day else journey_data['day_of_journey'].max()
                
                try:
                    for _, row in journey_data.iterrows():
                        day = row['day_of_journey']
                        
                        # Stop showing days after death
                        if death_day and day > death_day:
                            break
                            
                        # Parse current drugs and levels
                        current_drugs = self.parse_drug_data(row['current_drugs'])
                        if current_drugs:
                            # Show up to 3 drugs with their actual levels
                            drug_entries = []
                            for drug, level in current_drugs[:3]:
                                drug_entries.append(f"{drug}({level:.1f})")
                            drug_str = ", ".join(drug_entries)
                            if len(current_drugs) > 3:
                                drug_str += f" +{len(current_drugs)-3}more"
                        else:
                            drug_str = "none"
                        drug_str = f"{drug_str:<20}"  # Fixed width for alignment
                        
                        # Parse resistance data for current drugs
                        majority_r_data = self.parse_drug_data(row['resistance_majority_r'])
                        activity_r_data = self.parse_drug_data(row['resistance_activity_r'])
                        
                        # Get resistance levels for current drugs
                        maj_r_levels = []
                        act_r_levels = []
                        for drug_name, _ in current_drugs:
                            # Find resistance for this drug
                            maj_r = next((level for drug, level in majority_r_data if drug == drug_name), 0.0)
                            act_r = next((level for drug, level in activity_r_data if drug == drug_name), 0.0)
                            maj_r_levels.append(maj_r)
                            act_r_levels.append(act_r)
                        
                        maj_r_str = f"{max(maj_r_levels):.2f}" if maj_r_levels else "0.00"
                        act_r_str = f"{max(act_r_levels):.2f}" if act_r_levels else "0.00"
                        
                        sepsis = 'yes' if row['sepsis'] else 'no'
                        
                        # Determine death status and cause
                        death_status = "no"
                        death_cause = ""
                        
                        # Check for death from resolution_type
                        resolution_type = row['resolution_type']
                        if pd.notna(resolution_type) and 'Death' in str(resolution_type):
                            death_status = f"yes ({resolution_type})"
                        elif death_day and day == death_day:
                            death_status = "yes"
                            death_cause = self.determine_death_cause(row)
                        
                        # Add notes for key events
                        notes = []
                        if day in treatment_start_days:
                            # Add specific drug name when treatment starts
                            if current_drugs:
                                drug_names = [drug for drug, _ in current_drugs]
                                notes.append(f"started: {', '.join(drug_names)}")
                            else:
                                notes.append("treatment started")
                        if day in sepsis_start_days:
                            notes.append("sepsis onset")
                        if day in hospital_change_days:
                            notes.append(f"hospital: {row['hospital_status']}")
                        if death_cause:
                            notes.append(f"death: {death_cause}")
                        
                        note_str = "; ".join(notes) if notes else ""
                        
                        f.write(f"{day:3d} | {row['primary_bacteria_level']:8.3f} | {row['immunity_level']:8.3f} | "
                               f"{row['toxicity_level']:8.3f} | {drug_str} | {maj_r_str:10} | {act_r_str:10} | {sepsis.lower():6} | "
                               f"{row['hospital_status']:11} | {death_status:21} | {note_str}\n")
                except KeyboardInterrupt:
                    f.write(f"\n*** PROCESSING INTERRUPTED for Journey {journey_id} ***\n")
                    print(f"Processing interrupted for journey {journey_id}")
                    break
                except Exception as e:
                    f.write(f"\n*** ERROR PROCESSING Journey {journey_id}: {str(e)} ***\n")
                    print(f"Error processing journey {journey_id}: {str(e)}")
                    continue                # Add summary if death was detected
                if death_day:
                    f.write(f"\n*** DEATH DETECTED ON DAY {death_day} - Journey terminated ***\n")
                
                f.write("\n" + "="*80 + "\n\n")
        
        if self.verbose:
            print(f"Detailed text report saved: {filename}")
        return filename

    def generate_summary_report(self):
        """Generate comprehensive summary report."""
        if self.verbose:
            print(f"\n{'='*80}")
            print("INFECTION JOURNEY ANALYSIS SUMMARY REPORT")
            print(f"{'='*80}")
            print(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            
            print(f"\nDataset Overview:")
            print(f"  Total journey snapshots: {len(self.df):,}")
            print(f"  Unique journeys: {self.df['journey_id'].nunique():,}")
            print(f"  Unique individuals: {self.df['individual_id'].nunique():,}")
            print(f"  Average journey length: {self.df.groupby('journey_id')['day_of_journey'].max().mean():.1f} days")
            
            print(f"\nJourney Outcomes:")
            resolution_counts = self.journey_summary['resolution_type'].value_counts()
            for resolution, count in resolution_counts.items():
                percentage = count / len(self.journey_summary) * 100
                print(f"  {resolution}: {count:,} ({percentage:.1f}%)")
            
            print(f"\nInfection Characteristics:")
            print(f"  Journeys with sepsis: {self.journey_summary['developed_sepsis'].sum():,} ({self.journey_summary['developed_sepsis'].mean()*100:.1f}%)")
            print(f"  Journeys with treatment: {self.journey_summary['was_treated'].sum():,} ({self.journey_summary['was_treated'].mean()*100:.1f}%)")
            print(f"  Hospital acquired infections: {self.journey_summary['hospital_acquired'].sum():,} ({self.journey_summary['hospital_acquired'].mean()*100:.1f}%)")
            
            print(f"\nMost Common Bacteria:")
            bacteria_counts = self.journey_summary['primary_bacteria'].value_counts().head(10)
            for bacteria, count in bacteria_counts.items():
                percentage = count / len(self.journey_summary) * 100
                print(f"  {bacteria.replace('_', ' ').title()}: {count:,} ({percentage:.1f}%)")
            
            print(f"\nDemographics:")
            print(f"  Average age at onset: {self.journey_summary['age_at_onset'].mean()/365.25:.1f} years")
            print(f"  Sex distribution:")
            sex_counts = self.journey_summary['sex'].value_counts()
            for sex, count in sex_counts.items():
                percentage = count / len(self.journey_summary) * 100
                print(f"    {sex.title()}: {count:,} ({percentage:.1f}%)")
            
            print(f"\nRegional Distribution:")
            region_counts = self.journey_summary['region'].value_counts()
            for region, count in region_counts.items():
                percentage = count / len(self.journey_summary) * 100
                print(f"  {region}: {count:,} ({percentage:.1f}%)")

def main(verbose=False, num_timeline_plots=5):
    """Main function to run the analysis."""
    if verbose:
        print("Infection Journey Analysis Tool")
        print("=" * 50)
    
    # Initialize analyzer with verbose setting
    analyzer = InfectionJourneyAnalyzer(verbose=verbose)
    
    # Generate summary report
    analyzer.generate_summary_report()
    
    # Generate detailed text report
    if verbose:
        print(f"\nGenerating detailed text report for all journeys...")
    text_report_file = analyzer.generate_text_report()
    
    # Generate timeline plots for randomly selected journeys with sequential numbering  
    # Use journey_summary which properly handles unique journeys and resolution detection
    # Random sampling ensures equal probability for all journeys regardless of temporal order
    available_journeys = analyzer.journey_summary['journey_id'].sample(n=min(num_timeline_plots, len(analyzer.journey_summary)), random_state=None).values
    if verbose:
        print(f"\nTotal unique journeys available: {len(analyzer.journey_summary)}")
        print(f"Generating {len(available_journeys)} randomly selected individual journey timeline plots...")
    
    for i, journey_id in enumerate(available_journeys, 1):
        analyzer.view_individual_journey(journey_id=journey_id, sequential_number=i)
    
    if verbose:
        print(f"\nAvailable journey IDs (showing first 20): {list(analyzer.df['journey_id'].unique()[:20])}")
    
    # Create population-level visualizations
    state_counts = analyzer.plot_infection_states_over_time(max_days=30)
    
    # Calculate mortality analysis
    mortality_analysis = analyzer.calculate_30_day_mortality()
    
    if verbose:
        print(f"\nAnalysis complete! Files generated:")
        print(f"  📊 Figures: {analyzer.output_dir}/*.png")
        print(f"  📄 Text report: {text_report_file}")
        print(f"\nUse the following methods for further exploration:")
        print(f"  analyzer.view_individual_journey(journey_id=X)  # View specific journey")
        print(f"  analyzer.plot_infection_states_over_time()      # Population infection states")
        print(f"  analyzer.calculate_30_day_mortality()           # Mortality analysis")
        print(f"  analyzer.generate_text_report()                 # Generate detailed text report")
    
    return analyzer

if __name__ == "__main__":
    # Configuration is set at the top of this file
    # Modify NUM_TIMELINE_PLOTS and VERBOSE_OUTPUT variables to change behavior
    analyzer = main(verbose=VERBOSE_OUTPUT, num_timeline_plots=NUM_TIMELINE_PLOTS)