ALL_MECHANISMS = \
['EffluxAcrabTolc',
 'EffluxMexxyOprm',
 'EffluxMtrCde',
 'EffluxTetAbc',
 'Enzyme16sRrmt',
 'EnzymeAacAph',
 'EnzymeAmpcCmy',
 'EnzymeAmpcDha',
 'EnzymeBlaZ',
 'EnzymeCat',
 'EnzymeEsblCtxM',
 'EnzymeEsblShv',
 'EnzymeEsblTem',
 'EnzymeFosA',
 'EnzymeKpc',
 'EnzymeNdmVim',
 'EnzymeOxa48',
 'EnzymeOxaAcinetobacter',
 'GlobalEffluxPump',
 'GlobalPorinLoss',
 'ModificationMcr1',
 'Mutation23sRrna',
 'MutationFolatePathway',
 'MutationGyrAParCSecondary',
 'MutationGyrAPrimary',
 'MutationMprF',
 'MutationNitroreductase',
 'MutationPbpMosaic',
 'MutationRpoB',
 'PorinLossOmpk35_36',
 'PorinLossOprd',
 'ProtectionFusB',
 'ProtectionQnr',
 'ProtectionTetM',
 'TargetSiteCfr',
 'TargetSiteErmB',
 'TargetSitePbp2aMecA',
 'TargetSiteVanA',
 'TargetSiteVanB']

MECH_TO_DRUGS = \
{'EffluxAcrabTolc': ['tetracycline', 'doxycycline', 'minocycline', 'tigecycline', 'chloramphenicol', 'ciprofloxacin'],
 'EffluxMexxyOprm': ['tetracycline',
                     'doxycycline',
                     'minocycline',
                     'gentamicin',
                     'tobramycin',
                     'amikacin',
                     'chloramphenicol',
                     'ciprofloxacin'],
 'EffluxMtrCde': ['erythromycin',
                  'azithromycin',
                  'clarithromycin',
                  'penicillin_g',
                  'ampicillin',
                  'amoxicillin',
                  'piperacillin',
                  'ticarcillin',
                  'tetracycline',
                  'doxycycline',
                  'minocycline',
                  'chloramphenicol'],
 'EffluxTetAbc': ['tetracycline', 'doxycycline'],
 'Enzyme16sRrmt': ['gentamicin', 'tobramycin', 'amikacin'],
 'EnzymeAacAph': ['gentamicin', 'tobramycin', 'amikacin', 'streptomycin', 'neomycin'],
 'EnzymeAmpcCmy': ['penicillin_g',
                   'ampicillin',
                   'amoxicillin',
                   'piperacillin',
                   'ticarcillin',
                   'flucloxacillin',
                   'amoxicillin_clavulanate',
                   'ampicillin_sulbactam',
                   'piperacillin_tazobactam',
                   'ticarcillin_clavulanate',
                   'cephalexin',
                   'cefazolin',
                   'cefuroxime',
                   'ceftriaxone',
                   'ceftazidime',
                   'cefixime',
                   'cefepime',
                   'ceftaroline',
                   'ceftolozane_tazobactam',
                   'aztreonam'],
 'EnzymeAmpcDha': ['penicillin_g',
                   'ampicillin',
                   'amoxicillin',
                   'piperacillin',
                   'ticarcillin',
                   'flucloxacillin',
                   'amoxicillin_clavulanate',
                   'ampicillin_sulbactam',
                   'piperacillin_tazobactam',
                   'ticarcillin_clavulanate',
                   'cephalexin',
                   'cefazolin',
                   'cefuroxime',
                   'ceftriaxone',
                   'ceftazidime',
                   'cefixime',
                   'cefepime',
                   'ceftaroline',
                   'ceftolozane_tazobactam',
                   'aztreonam'],
 'EnzymeBlaZ': ['penicillin_g', 'ampicillin', 'amoxicillin', 'piperacillin', 'ticarcillin'],
 'EnzymeCat': ['chloramphenicol'],
 'EnzymeEsblCtxM': ['penicillin_g',
                    'ampicillin',
                    'amoxicillin',
                    'piperacillin',
                    'ticarcillin',
                    'flucloxacillin',
                    'cephalexin',
                    'cefazolin',
                    'cefuroxime',
                    'ceftriaxone',
                    'ceftazidime',
                    'cefixime',
                    'cefepime',
                    'ceftaroline',
                    'aztreonam'],
 'EnzymeEsblShv': ['penicillin_g',
                   'ampicillin',
                   'amoxicillin',
                   'piperacillin',
                   'ticarcillin',
                   'flucloxacillin',
                   'cephalexin',
                   'cefazolin',
                   'cefuroxime',
                   'ceftriaxone',
                   'ceftazidime',
                   'cefixime',
                   'cefepime',
                   'ceftaroline',
                   'aztreonam'],
 'EnzymeEsblTem': ['penicillin_g',
                   'ampicillin',
                   'amoxicillin',
                   'piperacillin',
                   'ticarcillin',
                   'flucloxacillin',
                   'cephalexin',
                   'cefazolin',
                   'cefuroxime',
                   'ceftriaxone',
                   'ceftazidime',
                   'cefixime',
                   'cefepime',
                   'ceftaroline',
                   'aztreonam'],
 'EnzymeFosA': ['fosfomycin'],
 'EnzymeKpc': ['penicillin_g',
               'ampicillin',
               'amoxicillin',
               'piperacillin',
               'ticarcillin',
               'flucloxacillin',
               'amoxicillin_clavulanate',
               'piperacillin_tazobactam',
               'ampicillin_sulbactam',
               'ticarcillin_clavulanate',
               'cephalexin',
               'cefazolin',
               'cefuroxime',
               'ceftriaxone',
               'ceftazidime',
               'cefixime',
               'cefepime',
               'ceftaroline',
               'ceftolozane_tazobactam',
               'aztreonam',
               'meropenem',
               'imipenem_c',
               'ertapenem'],
 'EnzymeNdmVim': ['penicillin_g',
                  'ampicillin',
                  'amoxicillin',
                  'piperacillin',
                  'ticarcillin',
                  'flucloxacillin',
                  'amoxicillin_clavulanate',
                  'piperacillin_tazobactam',
                  'ampicillin_sulbactam',
                  'ticarcillin_clavulanate',
                  'cephalexin',
                  'cefazolin',
                  'cefuroxime',
                  'ceftriaxone',
                  'ceftazidime',
                  'cefixime',
                  'cefepime',
                  'ceftaroline',
                  'ceftolozane_tazobactam',
                  'ceftazidime_avibactam',
                  'meropenem_vaborbactam',
                  'meropenem',
                  'imipenem_c',
                  'ertapenem'],
 'EnzymeOxa48': ['penicillin_g',
                 'ampicillin',
                 'amoxicillin',
                 'piperacillin',
                 'ticarcillin',
                 'flucloxacillin',
                 'amoxicillin_clavulanate',
                 'piperacillin_tazobactam',
                 'ampicillin_sulbactam',
                 'ticarcillin_clavulanate',
                 'cephalexin',
                 'cefazolin',
                 'cefuroxime',
                 'ceftriaxone',
                 'ceftazidime',
                 'cefixime',
                 'cefepime',
                 'ceftaroline',
                 'meropenem',
                 'imipenem_c',
                 'ertapenem',
                 'meropenem_vaborbactam'],
 'EnzymeOxaAcinetobacter': ['meropenem', 'imipenem_c', 'ertapenem', 'ceftazidime', 'cefepime', 'ceftazidime_avibactam'],
 'GlobalEffluxPump': ['tetracycline', 'doxycycline', 'minocycline', 'tigecycline', 'chloramphenicol', 'ciprofloxacin'],
 'GlobalPorinLoss': ['penicillin_g',
                     'ampicillin',
                     'amoxicillin',
                     'piperacillin',
                     'ticarcillin',
                     'flucloxacillin',
                     'amoxicillin_clavulanate',
                     'ampicillin_sulbactam',
                     'piperacillin_tazobactam',
                     'ticarcillin_clavulanate',
                     'ceftriaxone',
                     'ceftazidime',
                     'cefixime',
                     'cefepime',
                     'ceftolozane_tazobactam',
                     'ceftaroline',
                     'cefiderocol',
                     'aztreonam',
                     'aztreonam_avibactam',
                     'meropenem',
                     'imipenem_c',
                     'ertapenem',
                     'ciprofloxacin',
                     'levofloxacin',
                     'moxifloxacin',
                     'ofloxacin',
                     'gentamicin',
                     'tobramycin',
                     'amikacin'],
 'ModificationMcr1': ['colistin'],
 'Mutation23sRrna': ['erythromycin', 'azithromycin', 'clarithromycin'],
 'MutationFolatePathway': ['sulfanilamide', 'trim_sulf'],
 'MutationGyrAParCSecondary': ['ciprofloxacin', 'ofloxacin', 'levofloxacin', 'moxifloxacin'],
 'MutationGyrAPrimary': ['ciprofloxacin', 'ofloxacin'],
 'MutationMprF': ['daptomycin'],
 'MutationNitroreductase': ['metronidazole', 'nitrofurantoin', 'furazolidone'],
 'MutationPbpMosaic': ['penicillin_g',
                       'ampicillin',
                       'amoxicillin',
                       'piperacillin',
                       'ticarcillin',
                       'flucloxacillin',
                       'amoxicillin_clavulanate',
                       'ampicillin_sulbactam',
                       'piperacillin_tazobactam',
                       'ticarcillin_clavulanate',
                       'cephalexin',
                       'cefazolin',
                       'cefuroxime',
                       'ceftriaxone',
                       'ceftazidime',
                       'cefixime',
                       'cefepime',
                       'ceftaroline',
                       'ceftolozane_tazobactam',
                       'ceftazidime_avibactam',
                       'aztreonam'],
 'MutationRpoB': ['fidaxomicin', 'rifampicin'],
 'PorinLossOmpk35_36': ['penicillin_g',
                        'ampicillin',
                        'amoxicillin',
                        'piperacillin',
                        'ticarcillin',
                        'flucloxacillin',
                        'amoxicillin_clavulanate',
                        'ampicillin_sulbactam',
                        'piperacillin_tazobactam',
                        'ticarcillin_clavulanate',
                        'ceftriaxone',
                        'ceftazidime',
                        'cefixime',
                        'cefepime',
                        'ceftolozane_tazobactam',
                        'ceftaroline',
                        'cefiderocol',
                        'aztreonam',
                        'aztreonam_avibactam',
                        'meropenem',
                        'imipenem_c',
                        'ertapenem',
                        'ciprofloxacin',
                        'levofloxacin',
                        'moxifloxacin',
                        'ofloxacin',
                        'gentamicin',
                        'tobramycin',
                        'amikacin'],
 'PorinLossOprd': ['meropenem', 'imipenem_c', 'ertapenem'],
 'ProtectionFusB': ['fusidic_a'],
 'ProtectionQnr': ['ciprofloxacin', 'ofloxacin'],
 'ProtectionTetM': ['tetracycline', 'doxycycline', 'minocycline'],
 'TargetSiteCfr': ['linezolid', 'tedizolid', 'chloramphenicol', 'clindamycin', 'retapamulin'],
 'TargetSiteErmB': ['erythromycin', 'azithromycin', 'clarithromycin', 'clindamycin', 'quinu_dalfo'],
 'TargetSitePbp2aMecA': ['penicillin_g',
                         'ampicillin',
                         'amoxicillin',
                         'piperacillin',
                         'ticarcillin',
                         'flucloxacillin',
                         'amoxicillin_clavulanate',
                         'piperacillin_tazobactam',
                         'ampicillin_sulbactam',
                         'ticarcillin_clavulanate',
                         'cephalexin',
                         'cefazolin',
                         'cefuroxime',
                         'ceftriaxone',
                         'ceftazidime',
                         'cefixime',
                         'cefepime',
                         'ceftolozane_tazobactam',
                         'cefiderocol',
                         'ceftazidime_avibactam',
                         'meropenem_vaborbactam',
                         'aztreonam',
                         'aztreonam_avibactam',
                         'meropenem',
                         'imipenem_c',
                         'ertapenem'],
 'TargetSiteVanA': ['vancomycin', 'teicoplanin', 'dalbavancin'],
 'TargetSiteVanB': ['vancomycin']}

MECH_TO_GROUPS = \
{'EffluxAcrabTolc': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'EffluxMexxyOprm': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'EffluxMtrCde': ['Fastidious', 'EntericPathogen'],
 'EffluxTetAbc': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious'],
 'Enzyme16sRrmt': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'EnzymeAacAph': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'GramPositive'],
 'EnzymeAmpcCmy': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'EnzymeAmpcDha': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'EnzymeBlaZ': ['GramPositive', 'Helicobacter', 'Fastidious'],
 'EnzymeCat': ['ALL'],
 'EnzymeEsblCtxM': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'EnzymeEsblShv': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'EnzymeEsblTem': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'EnzymeFosA': ['Enterobacterales', 'NonFermenter', 'EntericPathogen'],
 'EnzymeKpc': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'EnzymeNdmVim': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'EnzymeOxa48': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'EnzymeOxaAcinetobacter': ['NonFermenter'],
 'GlobalEffluxPump': ['ALL'],
 'GlobalPorinLoss': ['ALL'],
 'ModificationMcr1': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'Mutation23sRrna': ['Helicobacter', 'EntericPathogen', 'Fastidious', 'GramPositive'],
 'MutationFolatePathway': ['ALL'],
 'MutationGyrAParCSecondary': ['ALL'],
 'MutationGyrAPrimary': ['ALL'],
 'MutationMprF': ['GramPositive'],
 'MutationNitroreductase': ['Enterobacterales', 'EntericPathogen', 'Anaerobe', 'Fastidious', 'Helicobacter'],
 'MutationPbpMosaic': ['ALL'],
 'MutationRpoB': ['ALL'],
 'PorinLossOmpk35_36': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'PorinLossOprd': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'ProtectionFusB': ['GramPositive'],
 'ProtectionQnr': ['Enterobacterales', 'NonFermenter', 'EntericPathogen', 'Fastidious', 'Anaerobe'],
 'ProtectionTetM': ['ALL'],
 'TargetSiteCfr': ['GramPositive', 'Anaerobe', 'Fastidious', 'Helicobacter'],
 'TargetSiteErmB': ['GramPositive', 'Anaerobe', 'Fastidious', 'Helicobacter'],
 'TargetSitePbp2aMecA': ['GramPositive', 'Helicobacter'],
 'TargetSiteVanA': ['GramPositive', 'Helicobacter'],
 'TargetSiteVanB': ['GramPositive', 'Helicobacter']}

BACTERIA_TO_GROUP = \
{'acinetobacter_baumannii': 'NonFermenter',
 'bacteroides_fragilis': 'Anaerobe',
 'bordetella_pertussis': 'Fastidious',
 'burkholderia_cepacia_complex': 'NonFermenter',
 'campylobacter_jejuni': 'Helicobacter',
 'chlamydia_trachomatis': 'Fastidious',
 'citrobacter_spp.': 'Enterobacterales',
 'clostridioides_difficile': 'Anaerobe',
 'enterobacter_cloacae': 'Enterobacterales',
 'enterobacter_spp.': 'Enterobacterales',
 'enterococcus_faecalis': 'GramPositive',
 'enterococcus_faecium': 'GramPositive',
 'escherichia_coli': 'Enterobacterales',
 'haemophilus_influenzae': 'Fastidious',
 'helicobacter_pylori': 'Helicobacter',
 'invasive_non-typhoidal_salmonella_spp.': 'Enterobacterales',
 'klebsiella_pneumoniae': 'Enterobacterales',
 'legionella_pneumophila': 'Fastidious',
 'listeria_monocytogenes': 'GramPositive',
 'mdr_mycobacterium_tuberculosis': 'Mycobacteria',
 'moraxella_catarrhalis': 'Fastidious',
 'morganella_spp.': 'Enterobacterales',
 'mycoplasma_genitalium': 'Fastidious',
 'mycoplasma_pneumoniae': 'Fastidious',
 'neisseria_gonorrhoeae': 'Fastidious',
 'neisseria_meningitidis': 'Fastidious',
 'p_stuartii': 'Enterobacterales',
 'proteus_spp.': 'Enterobacterales',
 'pseudomonas_aeruginosa': 'NonFermenter',
 'salmonella_enterica_serovar_paratyphi_a': 'Enterobacterales',
 'salmonella_enterica_serovar_typhi': 'Enterobacterales',
 'serratia_spp.': 'Enterobacterales',
 'shigella_spp.': 'Enterobacterales',
 'staphylococcus_aureus': 'GramPositive',
 'staphylococcus_epidermidis': 'GramPositive',
 'stenotrophomonas_maltophilia': 'NonFermenter',
 'streptococcus_agalactiae': 'GramPositive',
 'streptococcus_pneumoniae': 'GramPositive',
 'streptococcus_pyogenes': 'GramPositive',
 'treponema_pallidum': 'Spirochete',
 'vibrio_cholerae': 'EntericPathogen',
 'yersinia_enterocolitica': 'Enterobacterales'}


def get_relevant_mechanisms(bacteria_slug, drug_slug):
    group = BACTERIA_TO_GROUP.get(bacteria_slug)
    relevant = []
    for mech in ALL_MECHANISMS:
        req_drugs = MECH_TO_DRUGS.get(mech, [])
        # Species specific overrides based on mod.rs
        if mech == "PorinLossOmpk35_36" and bacteria_slug != "klebsiella_pneumoniae":
            continue
        if mech == "PorinLossOprd" and bacteria_slug != "pseudomonas_aeruginosa":
            continue
            
        if drug_slug in req_drugs or drug_slug in [d.replace('_', '') for d in req_drugs]:
            req_groups = MECH_TO_GROUPS.get(mech, [])
            if "ALL" in req_groups or group in req_groups:
                relevant.append(mech)
    relevant.sort()
    return relevant
